-- ================================================
-- B1 FULL 1-20: Tất cả câu hỏi
-- Import vào Supabase SQL Editor
-- ================================================

-- Xóa dữ liệu cũ (tùy chọn - bỏ comment nếu muốn xóa hết)
-- DELETE FROM questions;

-- ================================================
-- PHẦN 1: 32 câu hỏi cơ bản đầu tiên
-- ================================================

INSERT INTO questions (question_type, question_pl, question_vi, option_a_pl, option_a_vi, option_b_pl, option_b_vi, option_c_pl, option_c_vi, correct_answer, explanation_pl, explanation_vi) VALUES

-- Câu 1
('basic', 
'W tej sytuacji masz obowiązek zatrzymać pojazd?',
'Trong tình huống này bạn có bắt buộc phải dừng xe hay không?',
'Tak - ustąpić pierwszeństwa pieszym',
'Có - nhường đường cho người đi bộ',
'Nie - można kontynuować jazdę',
'Không - có thể tiếp tục đi',
'Tak - bo jest czerwone światło',
'Có - vì đèn đỏ',
'A',
'Masz obowiązek zatrzymać się i ustąpić pierwszeństwa pieszym przechodzącym przez przejście.',
'Bạn có nghĩa vụ dừng lại và nhường đường cho người đi bộ qua đường.'),

-- Câu 2
('basic', 
'W tej sytuacji masz obowiązek zatrzymać pojazd?',
'Trong tình huống này bạn có bắt buộc phải dừng xe hay không?',
'Tak - ustąpić pierwszeństwa pieszym',
'Có - nhường đường cho người đi bộ',
'Nie - nie ma pieszych na przejściu',
'Không - đường không có người đi bộ',
'Tak - bo jest znak STOP',
'Có - vì có biển báo stop',
'A',
'Masz obowiązek zatrzymać się przed przejściem dla pieszych i ustąpić im pierwszeństwa.',
'Bạn có nghĩa vụ dừng trước vạch qua đường và nhường đường cho người đi bộ.'),

-- Câu 3
('basic', 
'Czy możesz kontynuować jazdę w tej sytuacji?',
'Bạn có được phép tiếp tục lái xe trong tình huống này không?',
'Nie - musisz się zatrzymać',
'Không - phải dừng lại',
'Tak - droga jest pusta',
'Có - đường trống',
'Tak - jeśli jedziesz wystarczająco wolno',
'Có - nếu đi đủ chậm',
'B',
'Mimo pustej drogi, musisz zatrzymać się w wyznaczonym miejscu.',
'Dù đường trống, bạn vẫn phải dừng ở nơi được chỉ định.'),

-- Câu 4
('basic', 
'Czy możesz skręcić w prawo mimo sygnalizacji świetlnej?',
'Bạn có được phép rẽ phải bất chấp tín hiệu đèn không?',
'Nie - musisz przestrzegać sygnalizacji',
'Không - phải tuân theo đèn tín hiệu',
'Tak - gdy nie ma pieszych',
'Có - khi không có người đi bộ',
'Tak - zawsze dozwolone',
'Có - luôn luôn được phép',
'A',
'Musisz zatrzymać się na czerwonym świetle nawet przy skręcie w prawo.',
'Bạn phải dừng lại khi đèn đỏ dù đang rẽ phải.'),

-- Câu 5
('basic', 
'Czy możesz zawrócić na pasie oznaczonym tym znakiem?',
'Bạn có được phép quay đầu xe trên làn đường được đánh dấu bằng biển báo này không?',
'Nie - znak zakazu zawracania',
'Không - biển cấm quay đầu',
'Tak - jeśli bezpiecznie',
'Có - nếu an toàn',
'Tak - gdy nie ma pojazdów na przeciwległym pasie',
'Có - khi không có xe đối diện',
'A',
'Znak zakazu zawracania zabrania wykonywania tego manewru.',
'Biển cấm quay đầu không cho phép thực hiện thao tác này.'),

-- Câu 6
('basic', 
'Czy w tej sytuacji możesz spodziewać się następnego sygnału świetlnego - zielonego?',
'Trong tình huống này, bạn có nên mong đợi tín hiệu tiếp theo là màu xanh lá cây không?',
'Tak - po czerwonym musi być zielony',
'Có - đèn đỏ rồi phải sang xanh',
'Nie - może być żółty',
'Không - có thể là đèn vàng',
'Tak - zawsze tak jest',
'Có - luôn luôn như vậy',
'A',
'Po sygnale czerwonym następuje zielony, choć może być też sygnał żółty.',
'Sau tín hiệu đỏ là xanh, tuy nhiên cũng có thể là tín hiệu vàng.'),

-- Câu 7
('basic', 
'Czy w tej sytuacji możesz skręcić w prawo bez zatrzymywania się na sygnalizacji świetlnej?',
'Trong tình huống này, bạn có được phép rẽ phải mà không dừng ở đèn giao thông không?',
'Nie - musisz ustąpić pieszym',
'Không - phải dừng cho người đi bộ',
'Tak - gdy droga jest pusta',
'Có - khi đường trống',
'Tak - zawsze dozwolone',
'Có - luôn luôn được phép',
'A',
'Musisz zatrzymać się przed sygnalizacją i ustąpić pierwszeństwa pieszym.',
'Bạn phải dừng trước đèn tín hiệu và nhường đường cho người đi bộ.'),

-- Câu 8
('basic', 
'Czy sygnalizacja świetlna na Twoim pasie pozwala na zawracanie w tej sytuacji?',
'Tín hiệu đèn cho làn đường của bạn có cho phép bạn quay đầu xe trong tình huống này không?',
'Nie - dozwolony jest tylko skręt w lewo',
'Không - chỉ được phép rẽ trái',
'Tak - zielone światło pozwala',
'Có - đèn xanh cho phép',
'Tak - można zawracać',
'Có - được quay đầu luôn',
'A',
'Światło na Twoim pasie nie pozwala na zawracanie - dozwolony jest tylko skręt w lewo.',
'Đèn trên làn đường của bạn không cho phép quay đầu - chỉ được rẽ trái.'),

-- Câu 9
('basic', 
'Czy w tej sytuacji sygnał świetlny oznacza brak ryzyka kolizji z innymi uczestnikami ruchu?',
'Trong tình huống này, tín hiệu đèn được truyền đi có nghĩa là không có va chạm với những người tham gia giao thông khác khi lái xe sang bên phải?',
'Nie - nadal musisz ustąpić pierwszeństwa',
'Không - vẫn phải nhường đường',
'Tak - zielone światło oznacza bezpieczeństwo',
'Có - đèn xanh an toàn',
'Tak - nikogo nie ma',
'Có - không có ai cả',
'B',
'Zielone światło nie zwalnia z obowiązku ustąpienia pierwszeństwa pieszym.',
'Đèn xanh không miễn trừ nghĩa vụ nhường đường cho người đi bộ.'),

-- Câu 10
('basic', 
'Czy w tej sytuacji sygnał świetlny pozwala Ci przejechać przez sygnalizator?',
'Trong tình huống này, tín hiệu đèn truyền đi có cho phép bạn lái xe qua đèn giao thông không?',
'Nie - jest czerwone światło',
'Không - đèn đỏ',
'Tak - można jechać prosto',
'Có - có thể đi thẳng',
'Nie - musisz skręcić w prawo',
'Không - phải rẽ phải',
'A',
'Czerwone światło zabrania przejazdu przez skrzyżowanie.',
'Đèn đỏ cấm đi qua ngã tư.'),

-- Câu 11
('basic', 
'Czy możesz skręcić w prawo w tej sytuacji, pod warunkiem że nie utrudniasz ruchu?',
'Bạn có được phép rẽ phải trong tình huống này miễn là không gây cản trở giao thông không?',
'Nie - skręt w prawo jest zakazany',
'Không - rẽ phải bị cấm',
'Tak - dozwolone jest skręcanie w prawo',
'Có - được phép rẽ phải',
'Tak - gdy droga jest pusta',
'Có - khi đường trống',
'A',
'Skręt w prawo jest zabroniony znakiem B-42.',
'Rẽ phải bị cấm bởi biển báo B-42.'),

-- Câu 12
('basic', 
'Czy w tej sytuacji możesz zmienić pas podczas jazdy na wprost?',
'Trong tình huống này, bạn có được phép chuyển làn khi định đi thẳng không?',
'Tak - przerywana linia pozwala na zmianę pasa',
'Có - đường đứt nét cho phép',
'Nie - linia ciągła zabrania',
'Không - đường liền cấm',
'Tak - zawsze dozwolone',
'Có - luôn luôn được',
'A',
'Przerywana linia pozioma pozwala na zmianę pasa ruchu.',
'Đường đứt nét cho phép chuyển làn đường.'),

-- Câu 13
('basic', 
'Czy możesz spodziewać się rowerzystów na tej drodze?',
'Bạn có thể mong đợi những người đi xe đạp sắp tới trên con đường này không?',
'Tak - jest znak z rowerem',
'Có - có biển báo xe đạp',
'Nie - droga jest zakazana dla rowerów',
'Không - đường cấm xe đạp',
'Tak - zawsze są rowerzyści',
'Có - luôn có xe đạp',
'A',
'Znak D-6b informuje o przejściu dla pieszych i rowerzystów.',
'Biển báo D-6b thông báo về lối đi dành cho người đi bộ và xe đạp.'),

-- Câu 14
('basic', 
'Czy możesz wjechać na lewy pas w tej sytuacji?',
'Bạn có được phép đi vào làn đường bên trái trong tình huống này không?',
'Nie - wjazd jest zabroniony',
'Không - đường cấm',
'Tak - gdy potrzebujesz wyprzedzić',
'Có - khi cần vượt',
'Tak - gdy pas jest pusty',
'Có - đường trống',
'A',
'Znak B-34 zabrania wjazdu na lewy pas ruchu.',
'Biển báo B-34 cấm đi vào làn trái.'),

-- Câu 15
('basic', 
'Czy to oznakowanie poziome wyznacza miejsce bezwzględnego zatrzymania?',
'Biển báo ngang (vạch kẻ đường) này có đánh dấu nơi dừng tuyệt đối ngay cả khi không có phương tiện nào đi từ hai bên không?',
'Nie - tylko zatrzymanie w celu ustąpienia pierwszeństwa',
'Không - chỉ là dừng nhường đường',
'Tak - bezwzględne zatrzymanie',
'Có - dừng bắt buộc',
'Nie - nie ma obowiązku zatrzymania',
'Không - không bắt buộc dừng',
'B',
'Linia Sz - linia zatrzymania - wyznacza miejsce bezwzględnego zatrzymania.',
'Vạch Sz - vạch dừng - chỉ vị trí dừng bắt buộc.'),

-- Câu 16
('basic', 
'Czy w tej sytuacji widoczna linia przerywana wskazuje miejsce zatrzymania w związku ze znakiem STOP?',
'Trong tình huống này, đường đứt nét có thể nhìn thấy có cho biết vị trí dừng của bạn liên quan đến biển báo "dừng" không?',
'Nie - linia nie jest związana ze znakiem',
'Không - vạch không liên quan',
'Tak - linia wskazuje miejsce zatrzymania',
'Có - vạch chỉ vị trí dừng',
'Nie - to tylko linia ostrzegawcza',
'Không - chỉ là vạch cảnh báo',
'B',
'Linia przerywana wskazuje optymalne miejsce zatrzymania przy znaku STOP.',
'Đường đứt nét chỉ vị trí dừng tối ưu khi có biển báo STOP.'),

-- Câu 17
('basic', 
'Czy ta ciągła linia wskazuje miejsce zatrzymania związane ze znakiem STOP?',
'Vạch liền này có cho bạn biết nơi dừng xe liên quan đến biển báo "dừng lại" không?',
'Tak - linia wskazuje miejsce zatrzymania',
'Có - vạch chỉ vị trí dừng',
'Nie - nie ma znaczenia',
'Không - không có ý nghĩa',
'Tak - trzeba się zatrzymać na linii',
'Có - phải dừng ngay tại vạch',
'A',
'Linia ciągła w połączeniu ze znakiem STOP wyznacza miejsce zatrzymania.',
'Vạch liền kết hợp với biển báo STOP chỉ vị trí dừng.'),

-- Câu 18
('basic', 
'Zamierzasz zawrócić na tym skrzyżowaniu. Czy jedziesz prawidłowym pasem?',
'Bạn sẽ quay đầu xe tại giao lộ này. Bạn có đi đúng làn đường không?',
'Tak - prawidłowy pas',
'Có - đúng làn',
'Nie - musisz zmienić pas',
'Không - phải sang làn khác',
'Tak - można tutaj zawracać',
'Có - được quay đầu ở đây',
'A',
'Zawracanie dozwolone na tym pasie.',
'Quay đầu được phép trên làn đường này.'),

-- Câu 19
('basic', 
'Skręcasz w lewo na skrzyżowaniu. Czy oznakowanie poziome pozwala na wjazd na pas przy prawym brzegu jezdni?',
'Bạn rẽ trái ở ngã tư. Các biển báo ngang có cho phép bạn đi vào làn đường ở mép đường bên phải sau khi đi vào đường ngang không?',
'Tak - dozwolone',
'Có - được phép',
'Nie - ten pas jest zabroniony',
'Không - cấm đi làn đó',
'Tak - gdy nie ma pojazdów',
'Có - khi không có xe',
'A',
'Oznakowanie poziome pozwala na wjazd na pas przy prawym brzegu.',
'Biển báo ngang cho phép đi vào làn mép đường phải.'),

-- Câu 20
('basic', 
'Czy możesz skręcić w lewo tutaj i wjechać na stację benzynową?',
'Bạn có được phép rẽ trái tại điểm này vào trạm xăng không?',
'Nie - znak zakazu skrętu',
'Không - biển cấm rẽ',
'Tak - dozwolone',
'Có - được phép',
'Nie - musisz jechać dookoła',
'Không - phải đi vòng',
'A',
'Znak B-21 zabrania skrętu w lewo.',
'Biển báo B-21 cấm rẽ trái.'),

-- Câu 21
('basic', 
'Czy linia w kształcie trójkąta wskazuje miejsce zatrzymania w celu ustąpienia pierwszeństwa?',
'Vạch hình tam giác có hiển thị cho bạn biết nơi dừng xe để nhường đường không?',
'Tak - trójkąt oznacza ustąpienie pierwszeństwa',
'Có - vạch tam giác nhường đường',
'Nie - to tylko oznakowanie jezdni',
'Không - chỉ là vạch kẻ đường',
'Tak - trzeba się zatrzymać',
'Có - phải dừng tại đó',
'A',
'Linia w kształcie trójkąta wyznacza miejsce zatrzymania dla ustąpienia pierwszeństwa.',
'Vạch hình tam giác chỉ vị trí dừng để nhường đường.'),

-- Câu 22
('basic', 
'Czy możesz skręcić w lewo tutaj i wjechać na parking?',
'Bạn có thể rẽ trái vào điểm này vào bãi đậu xe không?',
'Nie - jest zakaz',
'Không - biển cấm',
'Tak - dozwolone',
'Có - được phép',
'Nie - trzeba wjechać inną bramą',
'Không - phải đi cổng khác',
'A',
'Znak B-1 zabrania wjazdu na parking od tej strony.',
'Biển báo B-1 cấm đi vào bãi đậu xe từ phía này.'),

-- Câu 23
('basic', 
'Zamierzasz odpocząć. Czy możesz skręcić w lewo tutaj i wjechać na parking?',
'Bạn sẽ đi nghỉ ngơi. Bạn có thể rẽ trái vào điểm này vào bãi đậu xe không?',
'Nie - zakaz zawracania',
'Không - biển cấm quay đầu',
'Tak - dozwolone',
'Có - được phép',
'Nie - musisz jechać dookoła',
'Không - phải đi vòng',
'A',
'Znak B-2 zabrania zawracania na tym odcinku drogi.',
'Biển báo B-2 cấm quay đầu trên đoạn đường này.'),

-- Câu 24
('basic', 
'Czy możesz skręcić w lewo ze swojego pasa w tej sytuacji?',
'Bạn có được phép rẽ trái từ làn đường của mình trong tình huống này không?',
'Nie - pas zabrania skrętu w lewo',
'Không - làn cấm rẽ trái',
'Tak - dozwolone',
'Có - được phép',
'Nie - musisz jechać prosto',
'Không - phải đi thẳng',
'A',
'Pas ruchu jest oznaczony strzałką tylko na wprost - skręt w lewo zabroniony.',
'Làn đường được đánh dấu mũi tên chỉ đi thẳng - cấm rẽ trái.'),

-- Câu 25
('basic', 
'Czy w tym momencie możesz wjechać na pas dla pojazdów nadjeżdżających z przeciwka?',
'Tại thời điểm này bạn có được phép đi vào làn đường dành cho xe ngược chiều không?',
'Nie - pas jest zabroniony',
'Không - làn cấm',
'Tak - pas jest pusty',
'Có - đường trống',
'Tak - gdy potrzebujesz wyprzedzić',
'Có - khi cần vượt',
'A',
'Wjazd na pas dla pojazdów nadjeżdżających z przeciwka jest surowo zabroniony.',
'Đi vào làn dành cho xe ngược chiều là cấm nghiêm ngặt.'),

-- Câu 26
('basic', 
'Czy możesz zmienić pas w tym miejscu, tuż przed przejściem dla pieszych?',
'Bạn có được phép chuyển làn đường ở nơi này, ngay trước lối đi bộ sang đường không?',
'Nie - zmiana pasa jest zabroniona w tym miejscu',
'Không - cấm chuyển làn ở đây',
'Tak - gdy pas jest pusty',
'Có - khi đường trống',
'Nie - trzeba zmienić pas wcześniej',
'Không - phải chuyển trước',
'A',
'Zmiana pasa ruchu jest zabroniona bezpośrednio przed przejściem dla pieszych.',
'Chuyển làn đường bị cấm ngay trước vạch qua đường cho người đi bộ.'),

-- Câu 27
('basic', 
'Czy widoczny trójkąt potwierdza ostrzeżenie o skrzyżowaniu z drogą z pierwszeństwem?',
'Biển báo ngang hình tam giác nhìn thấy có xác nhận cảnh báo về nơi giao nhau với đường ưu tiên không?',
'Tak - trójkąt potwierdza',
'Có - tam giác xác nhận',
'Nie - nie ma związku',
'Không - không liên quan',
'Tak - ostrzeżenie o niebezpieczeństwie',
'Có - cảnh báo nguy hiểm',
'A',
'Trójkąt potwierdza ostrzeżenie o skrzyżowaniu z drogą z pierwszeństwem przejazdu.',
'Tam giác xác nhận cảnh báo về giao nhau với đường ưu tiên.'),

-- Câu 28
('basic', 
'Czy możesz wjechać na sąsiedni pas po prawej w tej sytuacji?',
'Bạn có được phép đi vào làn bên phải liền kề trong tình huống này không?',
'Tak - przerywana linia pozwala',
'Có - đường đứt nét cho phép',
'Nie - linia ciągła zabrania',
'Không - đường liền cấm',
'Tak - zawsze dozwolone',
'Có - luôn được phép',
'A',
'Przerywana linia dzieląca pasy pozwala na zmianę pasa ruchu.',
'Đường đứt nét phân cách các làn cho phép chuyển làn.'),

-- Câu 29
('basic', 
'Czy widoczna poprzeczna linia przerywana wskazuje warunkowe miejsce zatrzymania pojazdu?',
'Đường đứt nét ngang có thể nhìn thấy có cho biết vị trí dừng có điều kiện của phương tiện không?',
'Tak - warunkowe zatrzymanie',
'Có - dừng có điều kiện',
'Nie - to nie jest miejsce zatrzymania',
'Không - không phải vị trí dừng',
'Tak - bezwzględne zatrzymanie',
'Có - phải dừng bắt buộc',
'A',
'Poprzeczna linia przerywana wyznacza warunkowe miejsce zatrzymania.',
'Đường đứt nét ngang chỉ vị trí dừng có điều kiện.'),

-- Câu 30
('basic', 
'Czy w tej sytuacji możesz zawrócić używając lewej zatoki?',
'Trong tình huống này, bạn có được phép quay đầu xe bằng cách sử dụng khoang bên trái không?',
'Tak - dozwolone użycie zatoki',
'Có - được phép sử dụng khoang',
'Nie - zawracanie zabronione',
'Không - cấm quay đầu',
'Tak - gdy nie ma pojazdów',
'Có - khi không có xe',
'A',
'Zatoka umożliwia bezpieczne zawracanie.',
'Khoang cho phép quay đầu xe an toàn.'),

-- Câu 31
('basic', 
'Czy masz prawo wyprzedzić ciężarówkę w tej sytuacji?',
'Bạn có quyền vượt xe tải trong tình huống này không?',
'Tak - warunki do wyprzedzania spełnione',
'Có - đủ điều kiện vượt',
'Nie - warunki nie są spełnione',
'Không - không đủ điều kiện',
'Tak - ciężarówka jedzie wolno',
'Có - xe tải đi chậm',
'A',
'Warunki do wyprzedzania są spełnione - masz prawo wyprzedzić ciężarówkę.',
'Điều kiện vượt được đáp ứng - bạn có quyền vượt xe tải.'),

-- Câu 32
('basic', 
'Zamierzasz jechać na wprost, a kierowca nadjeżdżającego pojazdu zamierza skręcić w lewo. Czy masz przed nim pierwszeństwo?',
'Bạn dự định đi thẳng và người điều khiển phương tiện đang tới chuẩn bị rẽ trái. Bạn có được ưu tiên hơn nó không?',
'Nie - skręcający w lewo ma pierwszeństwo',
'Không - người rẽ trái được ưu tiên',
'Tak - jadący na wprost ma pierwszeństwo',
'Có - đi thẳng được ưu tiên',
'Tak - nie ma pojazdu na przeciwległym pasie',
'Có - không có xe đối diện',
'B',
'Kierowca skręcający w lewo musi ustąpić pierwszeństwa pojazdom jadącym na wprost.',
'Người rẽ trái phải nhường đường cho xe đi thẳng.');

-- ================================================
-- PHẦN 2: 20 câu luật giao thông Bài 1
-- ================================================

INSERT INTO questions (question_type, question_pl, question_vi, option_a_pl, option_a_vi, option_b_pl, option_b_vi, option_c_pl, option_c_vi, correct_answer, explanation_pl, explanation_vi) VALUES

-- Câu 1
('special', 
'Zamierzasz skręcić w lewo, a kierowca nadjeżdżającego pojazdu zamierza jechać prosto. Czy masz przed nim pierwszeństwo?',
'Bạn định rẽ trái và người điều khiển phương tiện sắp tới định đi theo con đường phía trước. Bạn có được ưu tiên hơn họ không?',
'Nie - musisz ustąpić pierwszeństwa',
'Không - phải nhường đường',
'Tak - masz pierwszeństwo jako skręcający',
'Có - được ưu tiên vì rẽ trái',
'Tak - jazda na wprost nie ma znaczenia',
'Có - đi thẳng không quan trọng',
'A',
'Kierowca skręcający w lewo musi ustąpić pierwszeństwa pojazdom nadjeżdżającym z przeciwka.',
'Người lái xe rẽ trái phải nhường đường cho xe đi từ hướng ngược lại.'),

-- Câu 2
('special', 
'Zamierzasz skręcić w lewo. Czy masz obowiązek ustąpić pierwszeństwa wszystkim pojazdom na skrzyżowaniu?',
'Bạn định rẽ trái. Bạn có bắt buộc phải nhường quyền ưu tiên cho tất cả các phương tiện tại giao lộ không?',
'Tak - musisz ustąpić wszystkim',
'Có - phải nhường cho tất cả',
'Nie - tylko pojazdom z przeciwka',
'Không - chỉ nhường xe đối diện',
'Tak - przy skręcie w lewo',
'Có - khi rẽ trái',
'A',
'Przy skręcie w lewo musisz ustąpić pierwszeństwa wszystkim pojazdom nadjeżdżającym z przeciwka.',
'Khi rẽ trái, bạn phải nhường quyền ưu tiên cho tất cả xe đi từ hướng ngược lại.'),

-- Câu 3
('special', 
'Zamierzasz jechać prosto, a motocyklista zamierza skręcić w lewo. Czy musisz mu ustąpić pierwszeństwa?',
'Bạn định đi thẳng và người đi xe máy định rẽ trái. Bạn có phải nhường đường cho anh ấy không?',
'Tak - musisz ustąpić motocykliście',
'Có - phải nhường cho xe máy',
'Nie - jadący prosto ma pierwszeństwo',
'Không - đi thẳng được ưu tiên',
'Tak - zawsze ustępuj',
'Có - luôn luôn nhường',
'A',
'Motocyklista skręcający w lewo musi ustąpić pierwszeństwa pojazdom jadącym na wprost.',
'Người đi xe máy rẽ trái phải nhường đường cho xe đi thẳng.'),

-- Câu 4
('special', 
'Zamierzasz jechać prosto, a kierowca nadjeżdżający zamierza skręcić w lewo. Czy masz prawo go wyprzedzić?',
'Bạn định đi thẳng và người điều khiển phương tiện sắp tới định rẽ trái. Bạn có quyền vượt qua anh ta không?',
'Tak - jadący prosto ma pierwszeństwo',
'Có - đi thẳng được ưu tiên',
'Nie - musisz ustąpić pierwszeństwa',
'Không - phải nhường đường',
'Tak - możesz wyprzedzić',
'Có - có thể vượt',
'B',
'Kierowca skręcający w lewo musi ustąpić pierwszeństwa pojazdom jadącym na wprost.',
'Người rẽ trái phải nhường đường cho xe đi thẳng.'),

-- Câu 5
('special', 
'Zostałeś właśnie wyprzedzony przez pojazd przed sobą. Czy możesz natychmiast zwiększyć prędkość po wyprzedzeniu?',
'Bạn vừa bị chiếc xe phía trước vượt lên. Có được phép tăng tốc độ ngay sau khi bị vượt không?',
'Nie - nie wolno przyspieszać natychmiast',
'Không - cấm tăng tốc ngay',
'Tak - wolno przyspieszać',
'Có - được phép tăng',
'Tak - po 3 sekundach',
'Có - sau 3 giây',
'A',
'Po wyprzedzeniu nie wolno nagle przyspieszać, aby nie zagrozić wyprzedanemu pojazdowi.',
'Sau khi bị vượt, không được tăng tốc đột ngột để không gây nguy hiểm cho xe đã vượt qua.'),

-- Câu 6
('special', 
'Czy masz obowiązek zatrzymać się w razie potrzeby podczas omijania nieruchomej przeszkody?',
'Bạn có bắt buộc phải dừng lại khi cần thiết trong khi vượt qua chướng ngại vật cố định không?',
'Tak - musisz się zatrzymać gdy potrzeba',
'Có - phải dừng khi cần',
'Nie - możesz kontynuować jazdę',
'Không - được phép đi tiếp',
'Tak - zawsze musisz się zatrzymać',
'Có - luôn phải dừng',
'A',
'W razie potrzeby musisz się zatrzymać, aby bezpiecznie ominąć przeszkodę.',
'Khi cần thiết, bạn phải dừng lại để an toàn vượt qua chướng ngại vật.'),

-- Câu 7
('special', 
'Czy musisz zachować szczególną ostrożność omijając nieruchomy obiekt w tej sytuacji?',
'Bạn có phải đặc biệt thận trọng khi vượt qua một vật đứng yên trong tình huống này không?',
'Tak - musisz być szczególnie ostrożny',
'Có - phải thận trọng',
'Nie - obiekt nieruchomy jest bezpieczny',
'Không - vật đứng yên an toàn',
'Tak - gdy są piesi',
'Có - khi có người đi bộ',
'A',
'Omijając nieruchomy obiekt musisz zachować szczególną ostrożność.',
'Khi vượt qua vật đứng yên, bạn phải đặc biệt thận trọng.'),

-- Câu 8
('special', 
'Czy ta linia wskazuje miejsce, gdzie musisz zatrzymać się przed wjazdem na skrzyżowanie?',
'Vạch này có cho biết nơi bạn phải dừng lại trước khi vào giao lộ không?',
'Tak - linia wskazuje miejsce zatrzymania',
'Có - vạch chỉ nơi dừng',
'Nie - to tylko linia ostrzegawcza',
'Không - chỉ là vạch cảnh báo',
'Tak - zatrzymaj się na 3 sekundy',
'Có - dừng 3 giây',
'A',
'Linia zatrzymania wyznacza miejsce, gdzie musisz się zatrzymać przed skrzyżowaniem.',
'Vạch dừng chỉ vị trí bạn phải dừng trước khi vào giao lộ.'),

-- Câu 9
('special', 
'Czy ta linia wskazuje punkt zatrzymania zapewniający najlepszą widoczność na skrzyżowaniu?',
'Vạch này có chỉ dẫn điểm dừng đảm bảo tầm nhìn tốt nhất tại nơi giao nhau không?',
'Tak - najlepszy punkt zatrzymania',
'Có - điểm dừng tốt nhất',
'Nie - to zwykła linia',
'Không - chỉ vạch thường',
'Tak - trzeba się zatrzymać',
'Có - phải dừng tại đó',
'A',
'Linia wskazuje optymalny punkt zatrzymania zapewniający najlepszą widoczność.',
'Vạch chỉ điểm dừng tối ưu đảm bảo tầm nhìn tốt nhất.'),

-- Câu 10
('special', 
'Czy masz obowiązek zatrzymać się w wyznaczonym miejscu, nawet jeśli masz pewność, że nie ma innych pojazdów?',
'Bạn có bắt buộc phải dừng lại ở nơi được chỉ định ngay cả khi bạn đã chắc chắn rằng không có phương tiện nào khác đang chạy trên đường chính không?',
'Tak - bezwzględny obowiązek zatrzymania',
'Có - phải dừng bắt buộc',
'Nie - nie trzeba gdy droga pusta',
'Không - không cần nếu đường trống',
'Tak - zgodnie z przepisami',
'Có - theo luật',
'A',
'Masz obowiązek zatrzymać się w wyznaczonym miejscu niezależnie od sytuacji na drodze.',
'Bạn có nghĩa vụ dừng ở nơi được chỉ định bất kể tình hình trên đường.'),

-- Câu 11
('special', 
'Czy w tej sytuacji możesz wjechać na pas przy prawym brzegu jezdni?',
'Trong tình huống này, bạn có được phép lái xe vào làn đường sát mép đường bên phải không?',
'Tak - dozwolone',
'Có - được phép',
'Nie - zabronione',
'Không - cấm',
'Tak - gdy nie ma pieszych',
'Có - khi không có người đi bộ',
'A',
'Wjazd na pas przy prawym brzegu jest dozwolony.',
'Được phép đi vào làn mép đường bên phải.'),

-- Câu 12
('special', 
'Czy w tej sytuacji jesteś ostrzegany o jednym niebezpiecznym zakręcie w prawo?',
'Bạn có được cảnh báo trong tình huống này về một khúc cua nguy hiểm duy nhất ở bên phải không?',
'Tak - jest ostrzeżenie',
'Có - có cảnh báo',
'Nie - ostrzeżenie o zakręcie w lewo',
'Không - cảnh báo bên trái',
'Nie - brak ostrzeżenia',
'Không - không có cảnh báo',
'A',
'Znak A-1 ostrzega o niebezpiecznym zakręcie w prawo.',
'Biển báo A-1 cảnh báo khúc cua nguy hiểm bên phải.'),

-- Câu 13
('special', 
'Czy w tej sytuacji jesteś ostrzegany o kilku niebezpiecznych zakrętach w lewo?',
'Bạn có được cảnh báo trong tình huống này về một vài khúc cua nguy hiểm bên trái không?',
'Nie - tylko jeden zakręt',
'Không - chỉ một khúc cua',
'Tak - kilka zakrętów',
'Có - nhiều khúc cua',
'Tak - jeden zakręt',
'Có - một khúc cua',
'A',
'Znak A-2 ostrzega o kilku niebezpiecznych zakrętach, z których pierwszy jest w lewo.',
'Biển báo A-2 cảnh báo nhiều khúc cua nguy hiểm, khúc đầu tiên bên trái.'),

-- Câu 14
('special', 
'Czy jesteś ostrzegany o tych dwóch niebezpiecznych zakrętach?',
'Bạn có được cảnh báo trong tình huống 2 khúc cua nguy hiểm này không?',
'Nie - to są 3 zakręty',
'Không - là 3 khúc cua',
'Tak - dokładnie 2 zakręty',
'Có - đúng 2 khúc cua',
'Tak - jest ostrzeżenie',
'Có - có cảnh báo',
'A',
'Znak ostrzega o trzech kolejnych niebezpiecznych zakrętach.',
'Biển báo cảnh báo ba khúc cua liên tiếp nguy hiểm.'),

-- Câu 15
('special', 
'Czy w tej sytuacji jesteś ostrzegany o dwóch niebezpiecznych zakrętach, pierwszym w lewo?',
'Bạn có được cảnh báo trong tình huống này về hai khúc cua nguy hiểm, khúc cua đầu tiên bên trái không?',
'Tak - dokładnie tak',
'Có - đúng như vậy',
'Nie - pierwszy zakręt jest w prawo',
'Không - khúc đầu bên phải',
'Tak - jeden zakręt',
'Có - một khúc cua',
'A',
'Znak A-2 wskazuje dwa zakręty, pierwszy w lewo.',
'Biển báo A-2 chỉ hai khúc cua, khúc đầu bên trái.'),

-- Câu 16
('special', 
'Czy w tej sytuacji jesteś ostrzegany o skrzyżowaniu bez znaków pierwszeństwa?',
'Bạn có được cảnh báo trong tình huống này về một giao lộ không có biển báo ưu tiên không?',
'Tak - skrzyżowanie bez pierwszeństwa',
'Có - giao lộ không có ưu tiên',
'Nie - są znaki',
'Không - có biển báo',
'Tak - zwykłe skrzyżowanie',
'Có - giao lộ thường',
'A',
'Znak A-7 ostrzega o skrzyżowaniu dróg równorzędnych.',
'Biển báo A-7 cảnh báo giao nhau của các đường ngang hàng.'),

-- Câu 17
('special', 
'Jaka jest maksymalna dozwolona prędkość w obszarze zabudowanym?',
'Khi điều khiển phương tiện, tốc độ tối đa được phép trong khu vực đông dân cư là bao nhiêu?',
'50 km/h',
'50 km/h',
'30 km/h',
'30 km/h',
'60 km/h',
'60 km/h',
'A',
'Maksymalna prędkość w obszarze zabudowanym wynosi 50 km/h.',
'Tốc độ tối đa trong khu vực đông dân cư là 50 km/h.'),

-- Câu 18
('special', 
'Czy powinieneś zacząć hamować w tej sytuacji?',
'Bạn có nên bắt đầu phanh xe trong tình huống này không?',
'Tak - powinieneś hamować',
'Có - nên phanh',
'Nie - przyspieszaj',
'Không - tăng tốc',
'Tak - gdy jest czerwone światło',
'Có - khi đèn đỏ',
'A',
'Przy zbliżaniu się do sygnalizacji musisz być gotowy do zatrzymania.',
'Khi đến gần đèn tín hiệu, bạn phải sẵn sàng dừng lại.'),

-- Câu 19
('special', 
'Czy wraz z upływem czasu zdolność postrzegania znaków drogowych i sygnałów poprawia się?',
'Khi điều khiển phương tiện, khả năng nhận biết biển báo và tín hiệu trên đường của bạn có được cải thiện theo thời gian không?',
'Nie - nie poprawia się',
'Không - không cải thiện',
'Tak - poprawia się z wiekiem',
'Có - cải thiện theo tuổi',
'Tak - zawsze się poprawia',
'Có - luôn cải thiện',
'A',
'Zdolność postrzegania nie poprawia się automatycznie z czasem.',
'Khả năng nhận thức không tự động cải thiện theo thời gian.'),

-- Câu 20
('special', 
'Jedziesz z prędkością 30 km/h. Czy powinieneś zatrzymać pojazd przed sygnalizacją świetlną w tej sytuacji?',
'Bạn đang lái xe với tốc độ 30 km/h. Bạn có nên dừng xe trước đèn giao thông trong tình huống này không?',
'Tak - powinieneś się zatrzymać',
'Có - nên dừng',
'Nie - kontynuuj jazdę',
'Không - tiếp tục đi',
'Tak - gdy jest czerwone światło',
'Có - khi đèn đỏ',
'A',
'Przy żółtym świetle musisz się zatrzymać, jeśli możesz to zrobić bezpiecznie.',
'Khi đèn vàng, bạn phải dừng lại nếu có thể làm an toàn.');

-- ================================================
-- PHẦN 3: 12 câu biển báo cảnh báo (Bài 2)
-- ================================================

INSERT INTO questions (question_type, question_pl, question_vi, option_a_pl, option_a_vi, option_b_pl, option_b_vi, option_c_pl, option_c_vi, correct_answer, explanation_pl, explanation_vi) VALUES

-- Câu 1
('special', 
'Czy jesteś ostrzegany o progu zwalniającym na drodze?',
'Bạn có được cảnh báo trong tình huống này về một cái bướu trên đường nhằm làm chậm giao thông không?',
'Nie - brak progu',
'Không - không có bướu',
'Tak - jest próg',
'Có - có bướu',
'Tak - próg spowalniający',
'Có - bướu làm chậm',
'B',
'Znak A-5 ostrzega o progu zwalniającym na drodze.',
'Biển báo A-5 cảnh báo bướu đường làm chậm giao thông.'),

-- Câu 2
('special', 
'Czy jesteś ostrzegany o progu zwalniającym na drodze?',
'Bạn có được cảnh báo trong tình huống có bướu trên đường nhằm làm chậm giao thông không?',
'Tak - jest próg',
'Có - có bướu',
'Nie - brak progu',
'Không - không có',
'Tak - mały próg',
'Có - bướu nhỏ',
'A',
'Znak A-5 ostrzega o progu zwalniającym.',
'Biển báo A-5 cảnh báo bướu đường.'),

-- Câu 3
('special', 
'Czy tablica umieszczona pod tym znakiem ostrzegawczym wskazuje odległość znaku od niebezpiecznego miejsca?',
'Bảng đặt dưới biển cảnh báo này có cho biết khoảng cách của biển báo với điểm nguy hiểm không?',
'Tak - odległość',
'Có - khoảng cách',
'Nie - brak informacji',
'Không - không có',
'Tak - odległość w km',
'Có - khoảng cách km',
'A',
'Tabliczka pod znakiem wskazuje odległość do niebezpiecznego miejsca.',
'Bảng dưới biển báo chỉ khoảng cách đến nơi nguy hiểm.'),

-- Câu 4
('special', 
'Czy jesteś ostrzegany o zwężeniu drogi, które może utrudniać ruch?',
'Bạn có được cảnh báo trong tình huống đường bị thu hẹp có thể gây cản trở giao thông không?',
'Tak - zwężenie drogi',
'Có - đường thu hẹp',
'Nie - szeroka droga',
'Không - đường rộng',
'Tak - utrudnienie',
'Có - cản trở',
'A',
'Znak A-8 ostrzega o zwężeniu drogi.',
'Biển báo A-8 cảnh báo đường thu hẹp.'),

-- Câu 5
('special', 
'Czy jesteś ostrzegany o skrzyżowaniu z drogą z prawej strony?',
'Bạn có được cảnh báo trong tình huống này về một giao lộ với con đường bên phải không?',
'Nie - droga z lewej strony',
'Không - đường bên trái',
'Tak - skrzyżowanie z prawej',
'Có - giao lộ bên phải',
'Tak - zwykłe skrzyżowanie',
'Có - giao lộ thường',
'A',
'Znak A-4 ostrzega o skrzyżowaniu z drogą z prawej strony.',
'Biển báo A-4 cảnh báo giao nhau với đường bên phải.'),

-- Câu 6
('special', 
'Czy musisz przygotować się na utrudnienia w ruchu w tej sytuacji?',
'Bạn có cần chuẩn bị cho những trở ngại giao thông trong tình huống này không?',
'Tak - musisz się przygotować',
'Có - cần chuẩn bị',
'Nie - normalnie',
'Không - bình thường',
'Tak - są utrudnienia',
'Có - có trở ngại',
'A',
'W tej sytuacji musisz przygotować się na utrudnienia w ruchu.',
'Trong tình huống này bạn phải chuẩn bị cho trở ngại giao thông.'),

-- Câu 7
('special', 
'Czy jesteś ostrzegany o przejściu dla pieszych?',
'Bạn có được cảnh báo trong tình huống này về vạch kẻ đường dành cho người đi bộ qua đường không?',
'Tak - przejście dla pieszych',
'Có - vạch cho người đi bộ',
'Nie - zwykła jezdnia',
'Không - đường thường',
'Tak - piesi',
'Có - người đi bộ',
'A',
'Znak A-16b ostrzega o przejściu dla pieszych.',
'Biển báo A-16b cảnh báo vạch qua đường cho người đi bộ.'),

-- Câu 8
('special', 
'Czy jesteś ostrzegany o miejscu na drodze, gdzie często przebywają dzieci?',
'Bạn có được cảnh báo trong tình huống này về một địa điểm trên đường mà trẻ em thường xuyên lui tới hoặc địa điểm đó có gần không?',
'Tak - dzieci',
'Có - trẻ em',
'Nie - dorośli',
'Không - người lớn',
'Tak - szkoła',
'Có - trường học',
'A',
'Znak A-17 ostrzega o miejscu, gdzie mogą przebywać dzieci.',
'Biển báo A-17 cảnh báo nơi có thể có trẻ em.'),

-- Câu 9
('special', 
'Czy jesteś ostrzegany o możliwości napotkania zwierząt gospodarskich na drodze?',
'Bạn có được cảnh báo trong tình huống này về khả năng gặp phải động vật trang trại trên đường không?',
'Tak - zwierzęta gospodarskie',
'Có - động vật trang trại',
'Nie - dzikie zwierzęta',
'Không - động vật hoang dã',
'Tak - bydło',
'Có - gia súc',
'A',
'Znak A-18a ostrzega o możliwości napotkania zwierząt gospodarskich.',
'Biển báo A-18a cảnh báo khả năng gặp động vật trang trại.'),

-- Câu 10
('special', 
'Czy jesteś ostrzegany o możliwości napotkania dzikich zwierząt na drodze?',
'Bạn có được cảnh báo trong tình huống này về khả năng gặp động vật hoang dã trên đường không?',
'Tak - dzikie zwierzęta',
'Có - động vật hoang dã',
'Nie - zwierzęta domowe',
'Không - động vật nhà',
'Tak - zwierzęta leśne',
'Có - thú rừng',
'A',
'Znak A-18b ostrzega o możliwości napotkania dzikich zwierząt.',
'Biển báo A-18b cảnh báo khả năng gặp động vật hoang dã.'),

-- Câu 11
('special', 
'Czy jesteś ostrzegany o miejscu, gdzie zaczyna się ruch dwukierunkowy?',
'Bạn có được cảnh báo trong tình huống này về nơi giao thông hai chiều bắt đầu không?',
'Tak - ruch dwukierunkowy',
'Có - giao thông hai chiều',
'Nie - jednokierunkowy',
'Không - một chiều',
'Tak - droga dwukierunkowa',
'Có - đường hai chiều',
'A',
'Znak A-20 ostrzega o miejscu, gdzie ruch dwukierunkowy się zaczyna.',
'Biển báo A-20 cảnh báo nơi giao thông hai chiều bắt đầu.'),

-- Câu 12
('special', 
'Czy jesteś ostrzegany o stromej górce w tej sytuacji?',
'Bạn có được cảnh báo trong tình huống này là đường lên dốc không?',
'Nie - zjazd',
'Không - đường xuống dốc',
'Tak - podjazd',
'Có - lên dốc',
'Nie - równa droga',
'Không - đường phẳng',
'B',
'Znak A-11b ostrzega o stromej górce.',
'Biển báo A-11b cảnh báo đường lên dốc.');

-- ================================================
-- Hoàn thành!
-- ================================================
