-- ============================================================
-- 50 More Polish B1 Driving Test Questions
-- Topics: Warning signs, Prohibition signs, Mandatory signs,
--         Priority signs, Speed limits/markings, Traffic rules,
--         Vehicle equipment, Alcohol/drugs, First aid, Eco-driving
-- ============================================================

INSERT INTO questions (question_type, question_pl, question_vi, image_url, option_a_pl, option_a_vi, option_b_pl, option_b_vi, option_c_pl, option_c_vi, correct_answer, explanation_pl, explanation_vi) VALUES

-- ============================================================
-- 1. ADDITIONAL WARNING SIGNS (Znaki ostrzegawcze) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/PL_road_sign_A-3.svg/250px-PL_road_sign_A-3.svg.png', 'Ostrzeżenie o niebezpiecznym zjazdzie w prawo', 'Cảnh báo đường dốc xuống nguy hiểm bên phải', 'Ostrzeżenie o niebezpiecznym wzniesieniu', 'Cảnh báo đoạn đường dốc lên', 'Ostrzeżenie o ostrym zakręcie w lewo', 'Cảnh báo khúc cua gấp bên trái', 'A', 'Znak A-3 ostrzega przed niebezpiecznym zjazdem - spadkiem terenu, który może wpływać na przyczepność i hamowanie.', 'Biển A-3 cảnh báo đoạn đường dốc xuống nguy hiểm - độ dốc có thể ảnh hưởng đến độ bám và phanh.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/PL_road_sign_A-6a.svg/250px-PL_road_sign_A-6a.svg.png', 'Skrzyżowanie z drogą podporządkowaną po prawej', 'Giao nhau với đường không ưu tiên bên phải', 'Skrzyżowanie z drogą podporządkowaną po lewej', 'Giao nhau với đường không ưu tiên bên trái', 'Skrzyżowanie równorzędne', 'Ngã tư ngang nhau', 'A', 'Znak A-6a ostrzega o skrzyżowaniu z drogą podporządkowaną występującą po prawej stronie.', 'Biển A-6a cảnh báo giao nhau với đường không ưu tiên ở phía bên phải.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/PL_road_sign_A-10.svg/250px-PL_road_sign_A-10.svg.png', 'Ostrzeżenie o stromej drodze w dół', 'Cảnh báo đường dốc xuống rất dốc', 'Ostrzeżenie o stromej drodze w górę', 'Cảnh báo đường dốc lên rất dốc', 'Ostrzeżenie o niebezpiecznym zakręcie', 'Cảnh báo khúc cua nguy hiểm', 'A', 'Znak A-10 ostrzega przed stromą drogą w dół - nachylenie przekracza 10%.', 'Biển A-10 cảnh báo đoạn đường rất dốc xuống - độ dốc vượt quá 10%.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/PL_road_sign_A-11.svg/250px-PL_road_sign_A-11.svg.png', 'Ostrzeżenie o stromej drodze w górę', 'Cảnh báo đường dốc lên rất dốc', 'Ostrzeżenie o stromej drodze w dół', 'Cảnh báo đường dốc xuống rất dốc', 'Ostrzeżenie o nierównej nawierzchni', 'Cảnh báo mặt đường gồ ghề', 'A', 'Znak A-11 ostrzega przed stromą drogą w górę - nachylenie przekracza 10%.', 'Biển A-11 cảnh báo đoạn đường rất dốc lên - độ dốc vượt quá 10%.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/PL_road_sign_A-12.svg/250px-PL_road_sign_A-12.svg.png', 'Ostrzeżenie o nierównej nawierzchni', 'Cảnh báo mặt đường gồ ghề', 'Ostrzeżenie o zwężeniu jezdni', 'Cảnh báo mặt đường bị thu hẹp', 'Ostrzeżenie o wybojach', 'Cảnh báo ổ gà', 'A', 'Znak A-12 ostrzega przed nierówną nawierzchnią - dziury, wyboje, nierówności na drodze.', 'Biển A-12 cảnh báo mặt đường gồ ghề - ổ gà, lồi lõm, bề mặt không bằng phẳng.'),

-- ============================================================
-- 2. ADDITIONAL PROHIBITION SIGNS (Znaki zakazu) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PL_road_sign_B-3.svg/250px-PL_road_sign_B-3.svg.png', 'Zakaz skrętu w prawo', 'Cấm rẽ phải', 'Zakaz skrętu w lewo', 'Cấm rẽ trái', 'Zakaz wjazdu', 'Cấm đi vào', 'A', 'Znak B-3 zakazuje skrętu w prawo. Pojazd musi jechać prosto lub skręcić w lewo (jeśli dozwolone).', 'Biển B-3 cấm rẽ phải. Xe phải đi thẳng hoặc rẽ trái (nếu được phép).'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/PL_road_sign_B-4.svg/250px-PL_road_sign_B-4.svg.png', 'Zakaz skrętu w lewo', 'Cấm rẽ trái', 'Zakaz skrętu w prawo', 'Cấm rẽ phải', 'Zakaz zawracania', 'Cấm quay đầu', 'A', 'Znak B-4 zakazuje skrętu w lewo. Pojazd musi jechać prosto lub skręcić w prawo (jeśli dozwolone).', 'Biển B-4 cấm rẽ trái. Xe phải đi thẳng hoặc rẽ phải (nếu được phép).'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/PL_road_sign_B-8.svg/250px-PL_road_sign_B-8.svg.png', 'Zakaz zawracania', 'Cấm quay đầu', 'Zakaz wjazdu', 'Cấm đi vào', 'Zakaz skrętu', 'Cấm rẽ', 'A', 'Znak B-8 zakazuje zawracania. Nie wolno odwrócić kierunku jazdy na tym odcinku drogi.', 'Biển B-8 cấm quay đầu. Không được đổi hướng ngược lại trên đoạn đường này.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/PL_road_sign_B-34.svg/250px-PL_road_sign_B-34.svg.png', 'Ograniczenie prędkości do wskazanej wartości', 'Giới hạn tốc độ đến giá trị ghi trên biển', 'Zalecana prędkość', 'Tốc độ khuyến nghị', 'Minimalna prędkość', 'Tốc độ tối thiểu', 'A', 'Znak B-33 i B-34 to znaki ograniczenia prędkości - maksymalna dopuszczalna prędkość wynosi tyle, ile wskazano na znaku.', 'Biển B-33 và B-34 là biển giới hạn tốc độ - tốc độ tối đa cho phép là con số ghi trên biển.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/PL_road_sign_B-44.svg/250px-PL_road_sign_B-44.svg.png', 'Koniec zakazu postoju', 'Hết cấm đỗ xe', 'Zakaz postoju', 'Cấm đỗ xe', 'Strefa zamieszkania', 'Khu vực dân cư', 'A', 'Znak B-44 (żółta naklejka na B-35) oznacza koniec zakazu postoju w strefie na żółto.', 'Biển B-44 (nhãn vàng trên B-35) báo hiệu hết cấm đỗ xe trong khu vực được đánh dấu vàng.'),

-- ============================================================
-- 3. ADDITIONAL MANDATORY SIGNS (Znaki nakazu) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/PL_road_sign_C-3.svg/250px-PL_road_sign_C-3.svg.png', 'Nakaz jazdy w lewo', 'Bắt buộc rẽ trái', 'Nakaz jazdy w prawo', 'Bắt buộc rẽ phải', 'Nakaz jazdy prosto', 'Bắt buộc đi thẳng', 'A', 'Znak C-3 nakazuje jazdę w lewo. Kierowca musi skręcić w lewo na najbliższym skrzyżowaniu.', 'Biển C-3 bắt buộc rẽ trái. Người lái phải rẽ trái ở ngã tư gần nhất.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/PL_road_sign_C-6.svg/250px-PL_road_sign_C-6.svg.png', 'Nakaz jazdy z obu stron znaku', 'Bắt buộc đi từ hai phía của biển', 'Nakaz jazdy tylko w prawo', 'Bắt buộc chỉ rẽ phải', 'Nakaz jazdy tylko w lewo', 'Bắt buộc chỉ rẽ trái', 'A', 'Znak C-6 nakazuje jazdę z obu stron przeszkody - można ominąć znak z lewej lub prawej strony.', 'Biển C-6 bắt buộc đi từ hai phía của chướng ngại - có thể đi vòng qua biển từ trái hoặc phải.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/PL_road_sign_C-8.svg/250px-PL_road_sign_C-8.svg.png', 'Droga dla pieszych', 'Đường cho người đi bộ', 'Droga dla rowerów', 'Đường cho xe đạp', 'Droga dla pieszych i rowerów', 'Đường cho người đi bộ và xe đạp', 'A', 'Znak C-8 wyznacza drogę przeznaczoną wyłącznie dla pieszych.', 'Biển C-8 chỉ đường dành riêng cho người đi bộ.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/PL_road_sign_C-9.svg/250px-PL_road_sign_C-9.svg.png', 'Ścieżka dla rowerów i pieszych (piesi z lewej)', 'Làn đường cho xe đạp và người đi bộ (người đi bộ bên trái)', 'Ścieżka tylko dla rowerów', 'Làn đường chỉ cho xe đạp', 'Droga dla pieszych', 'Đường cho người đi bộ', 'A', 'Znak C-9 wyznacza ciąg pieszo-rowerowy - piesi mają wyznaczoną stronę (zazwyczaj lewą), rowerzyści poruszają się po drugiej stronie.', 'Biển C-9 chỉ đường đi bộ và xe đạp chung - người đi bộ có phần đường riêng (thường bên trái), người đi xe đạp đi ở phía còn lại.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/PL_road_sign_C-10.svg/250px-PL_road_sign_C-10.svg.png', 'Ścieżka dla rowerów i pieszych (piesi z prawej)', 'Làn đường cho xe đạp và người đi bộ (người đi bộ bên phải)', 'Ścieżka tylko dla pieszych', 'Làn đường chỉ cho người đi bộ', 'Droga dla rowerów', 'Đường cho xe đạp', 'A', 'Znak C-10 to ciąg pieszo-rowerowy z pieszymi po prawej stronie.', 'Biển C-10 là đường đi bộ và xe đạp chung với người đi bộ ở phía bên phải.'),

-- ============================================================
-- 4. ADDITIONAL PRIORITY SIGNS (Znaki pierwszeństwa) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/PL_road_sign_D-6b.svg/250px-PL_road_sign_D-6b.svg.png', 'Przejście dla pieszych', 'Vạch sang đường cho người đi bộ', 'Przejazd dla rowerzystów', 'Làn đường cho người đi xe đạp', 'Miejsce dla pieszych', 'Khu vực cho người đi bộ', 'A', 'Znak D-6b oznacza przejście dla pieszych - miejsce wyznaczone do przechodzenia przez jezdnię.', 'Biển D-6b chỉ vạch sang đường cho người đi bộ - nơi được quy định để đi qua đường.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/PL_road_sign_D-6c.svg/250px-PL_road_sign_D-6c.svg.png', 'Przejazd dla rowerzystów', 'Làn đường cho người đi xe đạp', 'Przejście dla pieszych', 'Vạch sang đường cho người đi bộ', 'Skrzyżowanie', 'Ngã tư', 'A', 'Znak D-6c oznacza przejazd dla rowerzystów - miejsce gdzie rowerzyści przejeżdżają przez jezdnię.', 'Biển D-6c chỉ làn đường cho người đi xe đạp qua đường.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/PL_road_sign_D-1a.svg/250px-PL_road_sign_D-1a.svg.png', 'Droga z pierwszeństwem (koniec)', 'Đường ưu tiên (hết)', 'Początek drogi z pierwszeństwem', 'Bắt đầu đường ưu tiên', 'Ustąp pierwszeństwa', 'Nhường đường', 'C', 'Znak D-1b oznacza koniec drogi z pierwszeństwem. Od tego miejsca obowiązują ogólne zasady pierwszeństwa.', 'Biển D-1b báo hiệu hết đường ưu tiên. Từ vị trí này áp dụng các quy tắc ưu tiên thông thường.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/PL_road_sign_D-2.svg/250px-PL_road_sign_D-2.svg.png', 'Koniec drogi z pierwszeństwem', 'Hết đường ưu tiên', 'Początek drogi z pierwszeństwem', 'Bắt đầu đường ưu tiên', 'Ustąp pierwszeństwa', 'Nhường đường', 'A', 'Znak D-2 (żółty prostokąt) oznacza koniec drogi z pierwszeństwem.', 'Biển D-2 (hình chữ nhật màu vàng) báo hiệu hết đường ưu tiên.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/PL_road_sign_D-4.svg/250px-PL_road_sign_D-4.svg.png', 'Ustąp pierwszeństwa', 'Nhường đường', 'Zatrzymaj się', 'Dừng lại', 'Zakaz wjazdu', 'Cấm đi vào', 'A', 'Znak D-1 (odwrócony trójkąt biały) oznacza ustąp pierwszeństwa - należy zwolnić i w razie potrzeby zatrzymać się.', 'Biển D-1 (tam giác ngược màu trắng) có nghĩa là nhường đường - cần giảm tốc độ và dừng lại nếu cần.'),

-- ============================================================
-- 5. ADDITIONAL ROAD MARKINGS & ZONES - 5 questions
-- ============================================================

('special', 'Co oznacza żółta linia na krawędzi jezdni?', 'Vạch màu vàng trên mép đường có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PL_road_sign_P-4.svg/250px-PL_road_sign_P-4.svg.png', 'Zakaz zatrzymywania się', 'Cấm dừng xe', 'Oznaczenie krawędzi jezdni', 'Đánh dấu mép đường', 'Zalecenie prędkości', 'Khuyến nghị tốc độ', 'A', 'Żółta linia ciągła na krawędzi jezdni oznacza zakaz zatrzymywania i postoju. Żółta przerywana - zakaz postoju.', 'Vạch liền màu vàng trên mép đường nghĩa là cấm dừng và đỗ xe. Vạch đứt đoạn vàng - cấm đỗ xe.'),

('special', 'Co oznacza zielona linia na krawędzi jezdni?', 'Vạch màu xanh lá trên mép đường có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PL_road_sign_P-4.svg/250px-PL_road_sign_P-4.svg.png', 'Strefa płatnego parkowania', 'Khu vực đỗ xe có phí', 'Darmowe parkowanie', 'Đỗ xe miễn phí', 'Zakaz parkowania', 'Cấm đỗ xe', 'A', 'Zielona linia na krawędzi jezdni oznacza strefę płatnego parkowania lub wyznaczone miejsce postoju.', 'Vạch màu xanh lá trên mép đường nghĩa là khu vực đỗ xe có thu phí hoặc nơi đỗ được chỉ định.'),

('special', 'Co oznacza strzałka kierunkowa na jezdni?', 'Mũi tên chỉ hướng trên mặt đường có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/PL_road_sign_P-1a.svg/250px-PL_road_sign_P-1a.svg.png', 'Wskazuje dozwolony kierunek jazdy', 'Chỉ hướng đi được phép', 'Zakazuje jazdy', 'Cấm đi', 'Ostrzega przed zakrętem', 'Cảnh báo khúc cua', 'A', 'Strzałki kierunkowe na jezdni wskazują dozwolony kierunek lub kierunki jazdy z danego pasa.', 'Mũi tên chỉ hướng trên đường chỉ hướng đi được phép từ làn đường đó.'),

('special', 'Co oznacza znak poziomy P-7 (linia przerywana)?', 'Vạch kẻ ngang đứt đoạn P-7 có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PL_road_sign_P-7.svg/250px-PL_road_sign_P-7.svg.png', 'Linia rozdziału pasów ruchu', 'Vạch phân cách các làn đường', 'Linia bezwzględnego zakazu', 'Vạch cấm tuyệt đối', 'Oznaczenie przejścia dla pieszych', 'Đánh dấu vạch sang đường', 'A', 'Linia P-7 (przerywana) rozdziela pasy ruchu o tym samym kierunku i nie zabrania ich przekraczania.', 'Vạch P-7 (đứt đoạn) phân chia các làn cùng chiều và không cấm chuyển làn.'),

('special', 'Co oznacza znak poziomy P-10 (obszar wyłączony)?', 'Vạch kẻ P-10 (khu vực loại trừ) có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/PL_road_sign_P-1a.svg/250px-PL_road_sign_P-1a.svg.png', 'Wydzielenie powierzchni wyłączonej z ruchu', 'Khu vực bị loại trừ khỏi giao thông', 'Strefa dozwolonego parkowania', 'Khu vực đỗ xe được phép', 'Przejście dla pieszych', 'Vạch sang đường', 'A', 'Znak P-10 (żółta kratka) oznacza powierzchnię wyłączoną z ruchu pojazdów, np. wysepki, powierzchnie przed przejazdami.', 'Biển P-10 (lưới vàng) chỉ khu vực không dành cho phương tiện, ví dụ gờ phân cách, khu vực trước đường ray.'),

-- ============================================================
-- 6. ADDITIONAL TRAFFIC RULES - 5 questions
-- ============================================================

('special', 'Kiedy można wyprzedzać pojazdy w Polsce?', 'Khi nào được phép vượt xe ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/PL_road_sign_D-6.svg/250px-PL_road_sign_D-6.svg.png', 'Tylko z lewej strony', 'Chỉ từ phía bên trái', 'Z prawej lub lewej strony', 'Từ bên phải hoặc trái', 'Tylko na autostradzie', 'Chỉ trên đường cao tốc', 'A', 'Wyprzedzanie odbywa się z lewej strony pojazdu wyprzedzanego. Z prawej można wyprzedzać tylko na drogach z dwoma pasami w jednym kierunku lub w korku.', 'Vượt xe được thực hiện từ phía bên trái của xe bị vượt. Từ bên phải chỉ được vượt trên đường có hai làn cùng chiều hoặc trong tắc đường.'),

('special', 'Jaka jest minimalna odległość między pojazdami podczas jazdy w tunelu?', 'Khoảng cách tối thiểu giữa các xe khi lái trong hầm là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', '50 metrów', '50 mét', '20 metrów', '20 mét', '100 metrów', '100 mét', 'A', 'W tunelu obowiązuje zakaz zatrzymywania się i minimalna odległość między pojazdami wynosząca co najmniej 50 metrów.', 'Trong hầm có cấm dừng xe và khoảng cách tối thiểu giữa các xe ít nhất là 50 mét.'),

('special', 'Czy można używać opon z kolcami w Polsce?', 'Có được sử dụng lốp có đinh tán ở Ba Lan không?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'Tak, ale tylko w okresie zimowym', 'Có, nhưng chỉ trong mùa đông', 'Tak, przez cały rok', 'Có, quanh năm', 'Nie, jest to zabronione', 'Không, bị cấm', 'A', 'Opony z kolcami dozwolone są w Polsce od 1 listopada do 31 marca, pod warunkiem, że temperatura powietrza jest niższa niż 7°C.', 'Lốp có đinh tán được phép ở Ba Lan từ 1 tháng 11 đến 31 tháng 3, với điều kiện nhiệt độ không khí dưới 7°C.'),

('special', 'Ile wynosi dopuszczalna masa całkowita zespołu pojazdów (ciągnik + przyczepa)?', 'Khối lượng toàn bộ cho phép của đoàn xe (đầu kéo + rơ moóc) là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/PL_road_sign_B-18.svg/250px-PL_road_sign_B-18.svg.png', '44 tony', '44 tấn', '40 ton', '40 tấn', '36 ton', '36 tấn', 'A', 'Dopuszczalna masa całkowita zespołu pojazdów w Polsce wynosi 44 tony dla standardowego zestawu drogowego (modułowego).', 'Khối lượng toàn bộ cho phép của đoàn xe ở Ba Lan là 44 tấn đối với bộ dây tiêu chuẩn (mô-đun).'),

('special', 'Co oznacza sygnał żółty świetlny?', 'Tín hiệu đèn vàng có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Zatrzymaj się przed skrzyżowaniem', 'Dừng lại trước ngã tư', 'Możesz jechać dalej', 'Có thể đi tiếp', 'Zwalniaj i przygotuj się do zatrzymania', 'Giảm tốc và chuẩn bị dừng lại', 'C', 'Żółty sygnał oznacza zakaz wjazdu, chyba że kierowca jest tak blisko, że gwałtowne hamowanie byłoby niebezpieczne. Zawsze należy zwolnić i przygotować się do zatrzymania.', 'Tín hiệu vàng nghĩa là cấm đi vào, trừ khi người lái đã quá gần mà phanh gấp sẽ nguy hiểm. Luôn phải giảm tốc và chuẩn bị dừng lại.'),

-- ============================================================
-- 7. ADDITIONAL VEHICLE EQUIPMENT - 5 questions
-- ============================================================

('special', 'Jakie opony są obowiązkowe zimą w Polsce?', 'Loại lốp nào bắt buộc phải dùng vào mùa đông ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'Opony zimowe lub wielosezonowe (M+S)', 'Lốp mùa đông hoặc đa mùa (M+S)', 'Opony letnie z łańcuchami', 'Lốp hè với xích', 'Opony越野', 'Lốp off-road', 'A', 'Zimą obowiązują opony zimowe lub wielosezonowe z oznaczeniem M+S (Mud and Snow). Minimalna głębokość bieżnika: 3 mm.', 'Vào mùa đông bắt buộc dùng lốp mùa đông hoặc đa mùa có ký hiệu M+S (Mud and Snow - Bùn và Tuyết). Độ sâu lốp tối thiểu: 3 mm.'),

('special', 'Co ile kilometrów należy sprawdzać ciśnienie w oponach?', 'Cần kiểm tra áp suất lốp sau bao nhiêu km?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'Co najmniej raz w miesiącu', 'Ít nhất mỗi tháng một lần', 'Raz na rok', 'Một lần mỗi năm', 'Przy każdym tankowaniu', 'Mỗi lần đổ xăng', 'A', 'Ciśnienie w oponach należy sprawdzać co najmniej raz w miesiącu oraz przed dłuższą podróżą. Nieprawidłowe ciśnienie zwiększa zużycie paliwa i opon.', 'Áp suất lốp cần được kiểm tra ít nhất mỗi tháng một lần và trước những chuyến đi dài. Áp suất không đúng làm tăng tiêu hao nhiên liệu và mòn lốp.'),

('special', 'Jaka jest rola systemu ABS w samochodzie?', 'Hệ thống ABS trên xe ô tô có vai trò gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'Zapobiega blokowaniu kół podczas hamowania', 'Ngăn chặn bánh xe bị khóa khi phanh', 'Zwiększa moc silnika', 'Tăng công suất động cơ', 'Oszczędza paliwo', 'Tiết kiệm nhiên liệu', 'A', 'System ABS (Anti-lock Braking System) zapobiega blokowaniu kół podczas gwałtownego hamowania, co pozwala kierowcy zachować kontrolę nad pojazdem.', 'Hệ thống ABS (Chống bó cứng phanh) ngăn chặn bánh xe bị khóa khi phanh gấp, giúp người lái giữ quyền kiểm soát xe.'),

('special', 'Co to jest system ESC/ESP?', 'Hệ thống ESC/ESP là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'System stabilizacji toru jazdy', 'Hệ thống ổn định hướng lái', 'System wspomagania parkowania', 'Hệ thống hỗ trợ đỗ xe', 'System hamowania awaryjnego', 'Hệ thống phanh khẩn cấp', 'A', 'ESC/ESP (Electronic Stability Control/Program) pomaga utrzymać kontrolę nad pojazdem w sytuacjach utraty przyczepności, np. na śliskiej nawierzchni.', 'ESC/ESP (Điều khiển ổn định điện tử) giúp giữ quyền kiểm soát xe trong tình huống mất độ bám, ví dụ trên mặt đường trơn trượt.'),

('special', 'Ile osób może podróżować samochodem z homologacją 4+1?', 'Một xe ô tô có giấy phép 4+1 có thể chở bao nhiêu người?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/PL_road_sign_B-18.svg/250px-PL_road_sign_B-18.svg.png', '4 osoby + kierowca', '4 người + tài xế', '5 osób łącznie', '5 người tổng cộng', '6 osób + kierowca', '6 người + tài xế', 'B', 'Homologacja 4+1 oznacza 4 miejsca dla pasażerów + 1 dla kierowcy, łącznie 5 osób w pojeździe.', 'Giấy phép 4+1 nghĩa là 4 chỗ cho hành khách + 1 cho tài xế, tổng cộng 5 người trên xe.'),

-- ============================================================
-- 8. ADDITIONAL FIRST AID - 5 questions
-- ============================================================

('special', 'Jakie jest prawidłowe ułożenie osoby nieprzytomnej, ale oddychającej?', 'Đặt người bất tỉnh nhưng còn thở ở tư thế nào là đúng?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Pozycja boczna ustalona (na boku)', 'Tư thế nằm nghiêng ổn định (nằm nghiêng)', 'Na plecach z nogami ugiętymi', 'Nằm ngửa với chân gập', 'Na brzuchu', 'Nằm sấp', 'A', 'Osobę nieprzytomną, ale oddychającą należy ułożyć w pozycji bocznej ustalonej (pozycja bezpieczna), aby zapewnić drożność dróg oddechowych.', 'Người bất tỉnh nhưng còn thở phải đặt ở tư thế nằm nghiêng ổn định (tư thế an toàn) để đảm bảo đường thở thông thoáng.'),

('special', 'Co robić w przypadku krwotoku z nosa?', 'Khi bị chảy máu cam (mũi) phải làm gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Pochylić głowę do przodu i uciskać skrzydełka nosa', 'Nghiêng đầu về phía trước và bóp cánh mũi', 'Odchylić głowę do tyłu', 'Ngửa đầu ra sau', 'Przykładać lód do czoła', 'Đặt đá lên trán', 'A', 'Przy krwotoku z nosa należy pochylić głowę do przodu, uciskać skrzydełka nosa przez 10-15 minut i oddychać przez usta.', 'Khi chảy máu mũi, cần nghiêng đầu về phía trước, bóp cánh mũi trong 10-15 phút và thở bằng miệng.'),

('special', 'Jak rozpoznać wstrząs anafilaktyczny?', 'Làm sao nhận biết sốc phản vệ?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Obrzęk twarzy, trudności w oddychaniu, wysypka', 'Mặt sưng, khó thở, phát ban', 'Ból głowy i zawroty', 'Đau đầu và chóng mặt', 'Gorączka i kaszel', 'Sốt và ho', 'A', 'Wstrząs anafilaktyczny objawia się: obrzękiem twarzy i gardła, trudnościami w oddychaniu, wysypką, bladością, przyspieszonym tętnem. Wymaga natychmiastowej pomocy medycznej!', 'Sốc phản vệ biểu hiện: mặt và горло sưng, khó thở, phát ban, xanh xao, mạch nhanh. Cần cấp cứu y tế ngay lập tức!'),

('special', 'Co oznacza skrót BLS?', 'Từ viết tắt BLS có nghĩa là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Basic Life Support (podstawowe zabiegi ratunkowe)', 'Hỗ trợ sự sống cơ bản', 'Badanie Lekarskie Specjalistyczne', 'Khám bệnh chuyên khoa', 'Bezpieczny Linia Samochodowa', 'Đường dây an toàn ô tô', 'A', 'BLS (Basic Life Support) to podstawowe zabiegi ratunkowe obejmujące: udrożnienie dróg oddechowych, sztuczne oddychanie i masaż serca.', 'BLS (Hỗ trợ sự sống cơ bản) bao gồm các biện pháp cấp cứu cơ bản: thông đường thở, thở nhân tạo và ép tim ngoài lồng ngực.'),

('special', 'Jak pomóc osobie z zadławieniem (ciało obce w drogach oddechowych)?', 'Làm thế nào giúp người bị nghẹn (dị vật trong đường thở)?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', '5 uderzeń w plecy + 5 uciśnięć brzucha (manewr Heimlicha)', '5 cái vỗ lưng + 5 lần ép bụng (nghiệm pháp Heimlich)', 'Podać dużo wody do picia', 'Cho uống nhiều nước', 'Położyć osobę na plecach', 'Đặt nằm ngửa', 'A', 'Przy zadławieniu należy wykonać 5 uderzeń w okolice międzyłopatkowe, a jeśli to nie pomoże - 5 uciśnięć nadbrzusza (manewr Heimlicha).', 'Khi bị nghẹn cần vỗ 5 lần vào vùng giữa hai xương bả vai, nếu không được thì ép 5 lần vùng thượng vị (nghiệm pháp Heimlich).'),

-- ============================================================
-- 9. ADDITIONAL ENVIRONMENT & ECOLOGY - 5 questions
-- ============================================================

('special', 'Co oznacza certyfikat ekologiczny pojazdu w Polsce?', 'Giấy chứng nhận sinh thái của xe ở Ba Lan có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Poziom emisji spalin (Euro 1-6)', 'Mức khí thải (Euro 1-6)', 'Rok produkcji pojazdu', 'Năm sản xuất xe', 'Pojemność silnika', 'Dung tích động cơ', 'A', 'Certyfikat ekologiczny (naklejka ecolabel) określa poziom emisji spalin pojazdu (Euro 1-6). Wyższy standard Euro = mniejsza emisja.', 'Giấy chứng nhận sinh thái (nhãn ecolabel) cho biết mức khí thải của xe (Euro 1-6). Tiêu chuẩn Euro cao hơn = ít khí thải hơn.'),

('special', 'Co to jest strefa ekologiczna (eko-strefa) w mieście?', 'Khu vực sinh thái (eco-zone) trong thành phố là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Strefa z ograniczeniem wjazdu dla pojazdów wysokoemisyjnych', 'Khu vực hạn chế xe phát thải cao', 'Strefa tylko dla pojazdów elektrycznych', 'Khu vực chỉ dành cho xe điện', 'Strefa płatnego parkowania', 'Khu vực đỗ xe có phí', 'A', 'Eko-strefa to obszar w mieście, gdzie obowiązują ograniczenia wjazdu dla pojazdów z wysoką emisją spalin. Wjazd bez odpowiedniej naklejki jest zabroniony.', 'Eko-strefa là khu vực trong thành phố có hạn chế đối với xe phát thải cao. Vào mà không có nhãn phù hợp bị cấm.'),

('special', 'Jak jazda na oponach z niskim ciśnieniem wpływa na środowisko?', 'Lái xe với lốp áp suất thấp ảnh hưởng đến môi trường như thế nào?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Zwiększa zużycie paliwa i emisję CO2', 'Tăng tiêu hao nhiên liệu và phát thải CO2', 'Zmniejsza hałas', 'Giảm tiếng ồn', 'Nie ma wpływu na środowisko', 'Không ảnh hưởng đến môi trường', 'A', 'Opony z ciśnieniem o 20% niższym od optymalnego zwiększają zużycie paliwa o około 10% i podnoszą emisję CO2.', 'Lốp có áp suất thấp hơn mức tối ưu 20% làm tăng tiêu hao nhiên liệu khoảng 10% và tăng phát thải CO2.'),

('special', 'Co oznacza etykieta energetyczna na oponie?', 'Nhãn năng lượng trên lốp có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Efektywność energetyczna opony (opór toczenia)', 'Hiệu quả năng lượng của lốp (lực cản lăn)', 'Klasę jakości opony', 'Cấp chất lượng lốp', 'Wytrzymałość na przebicie', 'Độ bền chống thủng', 'A', 'Etykieta energetyczna opony klasyfikuje opony według oporu toczenia (wpływ na zużycie paliwa) oraz przyczepności na mokrej nawierzchni.', 'Nhãn năng lượng của lốp phân loại lốp theo lực cản lăn (ảnh hưởng đến tiêu hao nhiên liệu) và khả năng bám trên đường ướt.'),

('special', 'Ile procent emisji CO2 pochodzi z transportu drogowego w Polsce?', 'Xe cộ đường bộ chiếm bao nhiêu phần trăm phát thải CO2 ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Około 90%', 'Khoảng 90%', 'Około 50%', 'Khoảng 50%', 'Około 30%', 'Khoảng 30%', 'A', 'Transport drogowy odpowiada za około 90% emisji CO2 z sektora transportu w Polsce.', 'Giao thông đường bộ chiếm khoảng 90% lượng phát thải CO2 từ ngành giao thông ở Ba Lan.'),

-- ============================================================
-- 10. ADDITIONAL PSYCHOLOGY & ATTITUDE - 5 questions
-- ============================================================

('special', 'Co to jest czas reakcji kierowcy?', 'Thời gian phản ứng của người lái xe là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Czas od zauważenia zagrożenia do podjęcia działania', 'Thời gian từ khi nhận ra nguy hiểm đến khi hành động', 'Czas hamowania', 'Thời gian phanh', 'Czas jazdy', 'Thời gian lái xe', 'A', 'Czas reakcji to okres od zauważenia zagrożenia (np. pieszego, przeszkody) do momentu rozpoczęcia hamowania lub omijania. Średnio wynosi około 1 sekundy.', 'Thời gian phản ứng là khoảng từ khi nhận ra nguy hiểm (ví dụ người đi bộ, chướng ngại) đến khi bắt đầu phanh hoặc tránh. Trung bình khoảng 1 giây.'),

('special', 'Jak alkohol wpływa na czas reakcji?', 'Rượu ảnh hưởng đến thời gian phản ứng như thế nào?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', 'Wydłuża czas reakcji', 'Kéo dài thời gian phản ứng', 'Skraca czas reakcji', 'Rút ngắn thời gian phản ứng', 'Nie ma wpływu', 'Không ảnh hưởng', 'A', 'Alkohol wydłuża czas reakcji nawet o 30-50%. Im wyższe stężenie, tym dłuższy czas reakcji i gorsza ocena sytuacji.', 'Rượu làm kéo dài thời gian phản ứng tới 30-50%. Nồng độ càng cao, thời gian phản ứng càng dài và đánh giá tình huống càng kém.'),

('special', 'Co to jest stres w ruchu drogowym?', 'Căng thẳng trong giao thông là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Stan napięcia psychicznego utrudniający bezpieczną jazdę', 'Trạng thái căng thẳng tâm lý làm khó lái xe an toàn', 'Strach przed policją', 'Sợ cảnh sát', 'Zmęczenie po długiej jeździe', 'Mệt sau khi lái xe đường dài', 'A', 'Stres w ruchu drogowym to stan napięcia psychicznego spowodowany np. korkami, hałasem, pośpiechem. Obniża koncentrację i wydłuża czas reakcji.', 'Căng thẳng trong giao thông là trạng thái căng thẳng tâm lý do kẹt xe, ồn ào, vội vàng. Làm giảm tập trung và kéo dài thời gian phản ứng.'),

('special', 'Jak należy zachować się wobec agresywnego kierowcy?', 'Cần đối xử với người lái xe hung dữ như thế nào?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Unikać konfrontacji, nie reagować agresją', 'Tránh đối đầu, không phản ứng hung dữ', 'Zatrąbić i pokazać gest', 'Bấm còi và chỉ tay', 'Przyspieszyć i wyprzedzić', 'Tăng tốc và vượt lên', 'A', 'Wobec agresywnego kierowcy należy zachować spokój, unikać kontaktu wzrokowego, nie reagować agresją i nie prowokować. Bezpieczeństwo jest najważniejsze.', 'Đối với người lái xe hung dữ cần giữ bình tĩnh, tránh nhìn vào mắt, không phản ứng hung dữ và không khiêu khích. An toàn là quan trọng nhất.'),

('special', 'Dlaczego zmęczenie jest niebezpieczne podczas jazdy?', 'Tại sao mệt mỏi nguy hiểm khi lái xe?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Może powodować zaśnięcie za kierownicą', 'Có thể gây ngủ gật khi đang lái xe', 'Zwiększa koncentrację', 'Tăng sự tập trung', 'Skraca czas reakcji', 'Rút ngắn thời gian phản ứng', 'A', 'Zmęczenie powoduje spadek koncentracji, wydłuża czas reakcji i może prowadzić do mikrosnu - krótkotrwałego zaśnięcia. Sen za kierownicą jest jedną z głównych przyczyn wypadków.', 'Mệt mỏi làm giảm tập trung, kéo dài thời gian phản ứng và có thể gây ra giấc ngủ ngắn - ngủ thiếp đi trong giây lát. Ngủ khi lái xe là một trong những nguyên nhân chính của tai nạn.');

-- ============================================================
-- END OF ADDITIONAL 50 QUESTIONS
-- ============================================================
