-- ============================================================
-- 50 Polish B1 Driving Test Questions
-- Topics: Warning signs, Prohibition signs, Mandatory signs,
--         Priority signs, Speed limits/markings, Traffic rules,
--         Vehicle equipment, Alcohol/drugs, First aid, Eco-driving
-- ============================================================

INSERT INTO questions (question_type, question_pl, question_vi, image_url, option_a_pl, option_a_vi, option_b_pl, option_b_vi, option_c_pl, option_c_vi, correct_answer, explanation_pl, explanation_vi) VALUES

-- ============================================================
-- 1. WARNING SIGNS (Znaki ostrzegawcze) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/PL_road_sign_A-1.svg/250px-PL_road_sign_A-1.svg.png', 'Ostrzeżenie o ostrym zakręcie w prawo', 'Cảnh báo có khúc cua gấp bên phải', 'Ostrzeżenie o niebezpiecznym zakręcie, najpierw w lewo, potem w prawo', 'Cảnh báo đoạn đường nguy hiểm, rẽ trái trước rồi rẽ phải', 'Ostrzeżenie o dwóch zakrętach', 'Cảnh báo có hai khúc cua', 'B', 'Znak A-1 oznacza niebezpieczne zakręty - najpierw w lewo, potem w prawo. To znak ostrzegawczy w kształcie trójkąta z czerwoną obwódką.', 'Biển A-1 báo hiệu đoạn đường nguy hiểm với các khúc cua liên tiếp - rẽ trái trước rồi rẽ phải. Đây là biển cảnh báo hình tam giác có viền đỏ.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/PL_road_sign_A-2.svg/250px-PL_road_sign_A-2.svg.png', 'Ostrzeżenie o ostrym zakręcie w lewo', 'Cảnh báo có khúc cua gấp bên trái', 'Ostrzeżenie o dwóch zakrętach - najpierw w prawo, potem w lewo', 'Cảnh báo có hai khúc cua - rẽ phải trước rồi rẽ trái', 'Ostrzeżenie o skrzyżowaniu', 'Cảnh báo có ngã tư', 'B', 'Znak A-2 oznacza niebezpieczne zakręty - najpierw w prawo, potem w lewo. To znak ostrzegawczy.', 'Biển A-2 báo hiệu đoạn đường nguy hiểm với các khúc cua liên tiếp - rẽ phải trước rồi rẽ trái. Đây là biển cảnh báo.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/PL_road_sign_A-7.svg/250px-PL_road_sign_A-7.svg.png', 'Ostrzeżenie o zwężeniu jezdni', 'Cảnh báo mặt đường bị thu hẹp', 'Ostrzeżenie o przejściu dla pieszych', 'Cảnh báo có vạch sang đường cho người đi bộ', 'Ostrzeżenie o skrzyżowaniu z drogą podporządkowaną', 'Cảnh báo giao nhau với đường không ưu tiên', 'C', 'Znak A-7 to znak ostrzegawczy "skrzyżowanie z drogą podporządkowaną" występującą po obu stronach.', 'Biển A-7 là biển cảnh báo "giao nhau với đường không ưu tiên" ở cả hai bên.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/PL_road_sign_A-16.svg/250px-PL_road_sign_A-16.svg.png', 'Ostrzeżenie o przejściu dla pieszych', 'Cảnh báo có vạch sang đường cho người đi bộ', 'Ostrzeżenie o dzieciach', 'Cảnh báo khu vực có trẻ em', 'Ostrzeżenie o rowerzystach', 'Cảnh báo có người đi xe đạp', 'B', 'Znak A-17 ostrzega przed dziećmi na drodze. Uwaga: A-16 to przejście dla pieszych, A-17 to dzieci.', 'Biển A-17 cảnh báo khu vực có trẻ em trên đường. Lưu ý: A-16 là vạch sang đường, A-17 là trẻ em.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/PL_road_sign_A-18a.svg/250px-PL_road_sign_A-18a.svg.png', 'Ostrzeżenie o zwierzętach hodowlanych', 'Cảnh báo có vật nuôi', 'Ostrzeżenie o dzikich zwierzętach', 'Cảnh báo có thú rừng', 'Ostrzeżenie o zwierzętach domowych', 'Cảnh báo có thú nuôi', 'B', 'Znak A-18b ostrzega przed dzikimi zwierzętami. Symbol jelenia oznacza dziką zwierzynę.', 'Biển A-18b cảnh báo có thú rừng. Biểu tượng hươu nghĩa là động vật hoang dã.'),

-- ============================================================
-- 2. PROHIBITION SIGNS (Znaki zakazu) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/PL_road_sign_B-1.svg/250px-PL_road_sign_B-1.svg.png', 'Zakaz wjazdu', 'Cấm đi vào', 'Zakaz ruchu w obu kierunkach', 'Cấm cả hai chiều', 'Zakaz zatrzymywania się', 'Cấm dừng xe', 'B', 'Znak B-1 oznacza zakaz ruchu w obu kierunkach - żaden pojazd nie może wjeżdżać.', 'Biển B-1 cấm cả hai chiều - không phương tiện nào được đi vào.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/PL_road_sign_B-2.svg/250px-PL_road_sign_B-2.svg.png', 'Zakaz wjazdu w jednym kierunku', 'Cấm đi vào một chiều', 'Zakaz skrętu w lewo', 'Cấm rẽ trái', 'Zakaz wyprzedzania', 'Cấm vượt', 'A', 'Znak B-2 oznacza zakaz wjazdu - dotyczy jednego kierunku, ale zabrania wjazdu wszystkim pojazdom.', 'Biển B-2 cấm đi vào - áp dụng cho một chiều nhưng cấm tất cả phương tiện đi vào.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/PL_road_sign_B-25.svg/250px-PL_road_sign_B-25.svg.png', 'Zakaz wyprzedzania', 'Cấm vượt', 'Zakaz zatrzymywania się', 'Cấm dừng xe', 'Koniec zakazu wyprzedzania', 'Hết cấm vượt', 'C', 'Znak B-25 oznacza koniec zakazu wyprzedzania. Biały znak z ukośnymi liniami oznacza koniec ograniczenia.', 'Biển B-25 báo hiệu hết cấm vượt. Biển trắng với các vạch chéo là biển báo hết hạn chế.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/PL_road_sign_B-36.svg/250px-PL_road_sign_B-36.svg.png', 'Zakaz postoju', 'Cấm đỗ xe', 'Zakaz zatrzymywania się', 'Cấm dừng xe', 'Zakaz ruchu pieszych', 'Cấm người đi bộ', 'B', 'Znak B-36 oznacza zakaz zatrzymywania się - nie można ani parkować, ani nawet zatrzymać się na chwilę.', 'Biển B-36 cấm dừng xe - không được đỗ xe và cũng không được dừng lại dù chỉ một chút.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/PL_road_sign_B-21.svg/250px-PL_road_sign_B-21.svg.png', 'Zakaz skrętu w lewo', 'Cấm rẽ trái', 'Zakaz wyprzedzania przez samochody ciężarowe', 'Cấm xe tải vượt', 'Zakaz zawracania', 'Cấm quay đầu', 'B', 'Znak B-25 zabrania wyprzedzania. Znak B-21 to zakaz skrętu w lewo. Pytanie dotyczy zakazu wyprzedzania przez pojazdy powyżej 3.5t.', 'Biển B-25 cấm vượt. Biển B-21 cấm rẽ trái. Câu hỏi đề cập đến cấm xe tải trên 3.5 tấn vượt.'),

-- ============================================================
-- 3. MANDATORY SIGNS (Znaki nakazu) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/PL_road_sign_C-1.svg/250px-PL_road_sign_C-1.svg.png', 'Nakaz jazdy w prawo', 'Bắt buộc rẽ phải', 'Nakaz jazdy prosto', 'Bắt buộc đi thẳng', 'Nakaz jazdy w lewo', 'Bắt buộc rẽ trái', 'A', 'Znak C-1 nakazuje jazdę w prawo. To okrągły znak niebieski z białą strzałką.', 'Biển C-1 bắt buộc rẽ phải. Đây là biển tròn màu xanh với mũi tên trắng.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/PL_road_sign_C-2.svg/250px-PL_road_sign_C-2.svg.png', 'Nakaz jazdy prosto', 'Bắt buộc đi thẳng', 'Nakaz jazdy w prawo', 'Bắt buộc rẽ phải', 'Nakaz jazdy w lewo', 'Bắt buộc rẽ trái', 'A', 'Znak C-2 nakazuje jazdę prosto. To okrągły znak niebieski z białą strzałką skierowaną do góry.', 'Biển C-2 bắt buộc đi thẳng. Đây là biển tròn màu xanh với mũi tên trắng hướng lên.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/PL_road_sign_C-5.svg/250px-PL_road_sign_C-5.svg.png', 'Nakaz jazdy z lewej strony znaku', 'Bắt buộc đi từ phía trái của biển', 'Nakaz jazdy z prawej strony znaku', 'Bắt buộc đi từ phía phải của biển', 'Nakaz jazdy prosto', 'Bắt buộc đi thẳng', 'B', 'Znak C-5 nakazuje jazdę z prawej strony znaku - można jechać tylko z prawej strony tej przeszkody.', 'Biển C-5 bắt buộc đi từ phía phải của biển - chỉ được đi từ phía phải của chướng ngại vật này.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Droga dla rowerów', 'Đường dành cho xe đạp', 'Droga dla pieszych', 'Đường cho người đi bộ', 'Droga dla pojazdów', 'Đường cho xe cộ', 'A', 'Znak C-13 oznacza drogę przeznaczoną wyłącznie dla rowerzystów.', 'Biển C-13 chỉ đường dành riêng cho xe đạp.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/PL_road_sign_C-16.svg/250px-PL_road_sign_C-16.svg.png', 'Droga dla pieszych i rowerów', 'Đường cho người đi bộ và xe đạp', 'Droga dla rowerów', 'Đường cho xe đạp', 'Koniec drogi dla rowerów', 'Hết đường cho xe đạp', 'A', 'Znak C-16/13 oznacza drogę dla pieszych i rowerów - wspólny ciąg pieszo-rowerowy.', 'Biển C-16/13 chỉ đường dành cho cả người đi bộ và xe đạp - đường đi bộ và xe đạp chung.'),

-- ============================================================
-- 4. PRIORITY SIGNS (Znaki pierwszeństwa) - 5 questions
-- ============================================================

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/PL_road_sign_D-1.svg/250px-PL_road_sign_D-1.svg.png', 'Droga z pierwszeństwem', 'Đường ưu tiên', 'Ustąp pierwszeństwa', 'Nhường đường', 'Koniec drogi z pierwszeństwem', 'Hết đường ưu tiên', 'A', 'Znak D-1 oznacza drogę z pierwszeństwem - na tej drodze mamy pierwszeństwo przejazdu.', 'Biển D-1 chỉ đường ưu tiên - trên đường này chúng ta được quyền ưu tiên.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/PL_road_sign_D-2.svg/250px-PL_road_sign_D-2.svg.png', 'Droga z pierwszeństwem', 'Đường ưu tiên', 'Koniec drogi z pierwszeństwem', 'Hết đường ưu tiên', 'Ustąp pierwszeństwa', 'Nhường đường', 'B', 'Znak D-2 oznacza koniec drogi z pierwszeństwem. Od tego miejsca obowiązują ogólne zasady pierwszeństwa.', 'Biển D-2 báo hết đường ưu tiên. Từ vị trí này áp dụng các quy tắc ưu tiên thông thường.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/PL_road_sign_D-3.svg/250px-PL_road_sign_D-3.svg.png', 'Droga z pierwszeństwem', 'Đường ưu tiên', 'Ustąp pierwszeństwa', 'Nhường đường', 'Skrzyżowanie z drogą podporządkowaną', 'Giao nhau với đường không ưu tiên', 'B', 'Znak D-3 (STOP) nakazuje bezwzględne zatrzymanie się przed skrzyżowaniem i ustąpienie pierwszeństwa.', 'Biển D-3 (STOP) bắt buộc dừng xe tuyệt đối trước ngã tư và nhường đường.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/PL_road_sign_A-6b.svg/250px-PL_road_sign_A-6b.svg.png', 'Skrzyżowanie z drogą podporządkowaną po lewej', 'Giao nhau với đường không ưu tiên bên trái', 'Skrzyżowanie z drogą podporządkowaną po prawej', 'Giao nhau với đường không ưu tiên bên phải', 'Skrzyżowanie dróg równorzędnych', 'Giao nhau các đường ngang nhau', 'A', 'Znak A-6a oznacza skrzyżowanie z drogą podporządkowaną występującą po stronie lewej.', 'Biển A-6a báo giao nhau với đường không ưu tiên ở phía bên trái.'),

('basic', 'Co oznacza ten znak drogowy?', 'Biển báo này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/PL_road_sign_E-1.svg/250px-PL_road_sign_E-1.svg.png', 'Przejazd kolejowy z zaporami', 'Chỗ qua đường ray có rào chắn', 'Przejazd kolejowy bez zapór', 'Chỗ qua đường ray không có rào chắn', 'Stacja kolejowa', 'Ga xe lửa', 'B', 'Znak E-1 (krzyż św. Andrzeja bez barierki) oznacza przejazd kolejowy bez zapór - zachowaj szczególną ostrożność.', 'Biển E-1 (thánh giá chữ A không có rào chắn) báo chỗ qua đường ray không có rào chắn - cần đặc biệt cẩn thận.'),

-- ============================================================
-- 5. SPEED LIMITS AND ROAD MARKINGS - 5 questions
-- ============================================================

('special', 'Jaka jest dopuszczalna prędkość pojazdu osobowego w terenie zabudowanym w Polsce?', 'Tốc độ cho phép của xe ô tô con trong khu vực đông dân cư ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/PL_road_sign_B-33.svg/250px-PL_road_sign_B-33.svg.png', '50 km/h', '50 km/h', '60 km/h', '60 km/h', '70 km/h', '70 km/h', 'A', 'W terenie zabudowanym dopuszczalna prędkość w ciągu dnia wynosi 50 km/h. W nocy (od 23:00 do 5:00) obowiązuje ograniczenie 50 km/h z możliwością ograniczenia do 30 km/h przez zarządcę drogi.', 'Trong khu vực đông dân cư, tốc độ cho phép ban ngày là 50 km/h. Ban đêm (từ 23:00 đến 5:00) áp dụng giới hạn 50 km/h có thể giảm xuống 30 km/h theo quyết định của cơ quan quản lý đường.'),

('special', 'Jaka jest dopuszczalna prędkość na autostradzie w Polsce?', 'Tốc độ cho phép trên đường cao tốc ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/PL_road_sign_E-17a.svg/250px-PL_road_sign_E-17a.svg.png', '120 km/h', '120 km/h', '130 km/h', '130 km/h', '140 km/h', '140 km/h', 'C', 'Na autostradzie w Polsce dopuszczalna prędkość wynosi 140 km/h dla samochodów osobowych.', 'Trên đường cao tốc ở Ba Lan, tốc độ cho phép là 140 km/h đối với xe ô tô con.'),

('special', 'Jaka jest dopuszczalna prędkość na drodze ekspresowej w Polsce?', 'Tốc độ cho phép trên đường cao tốc loại express ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/PL_road_sign_E-17b.svg/250px-PL_road_sign_E-17b.svg.png', '100 km/h', '100 km/h', '110 km/h', '110 km/h', '120 km/h', '120 km/h', 'C', 'Na drodze ekspresowej (z dwoma jezdniami) dopuszczalna prędkość wynosi 120 km/h.', 'Trên đường express (có hai làn đường) tốc độ cho phép là 120 km/h.'),

('special', 'Co oznacza ta linia na jezdni?', 'Vạch kẻ trên đường này có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/PL_road_sign_P-1a.svg/250px-PL_road_sign_P-1a.svg.png', 'Linia ciągła - zakaz przejeżdżania', 'Vạch liền - cấm vượt qua', 'Linia przerywana - można wyprzedzać', 'Vạch đứt đoạn - được phép vượt', 'Linia ostrzegawcza', 'Vạch cảnh báo', 'A', 'Linia ciągła (P-1) oznacza zakaz przejeżdżania - nie wolno jej przekraczać ani najeżdżać na nią.', 'Vạch liền (P-1) có nghĩa là cấm vượt qua - không được phép vượt qua hoặc đè lên vạch.'),

('special', 'Co oznacza podwójna linia ciągła na jezdni?', 'Vạch liền kép trên đường có ý nghĩa gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PL_road_sign_P-4.svg/250px-PL_road_sign_P-4.svg.png', 'Można wyprzedzać', 'Được phép vượt', 'Bezwzględny zakaz wyprzedzania', 'Cấm vượt tuyệt đối', 'Ostrzeżenie o niebezpieczeństwie', 'Cảnh báo nguy hiểm', 'B', 'Podwójna linia ciągła (P-4) oznacza bezwzględny zakaz wyprzedzania i przejeżdżania - obowiązuje cały czas, nawet jeśli nie ma znaku.', 'Vạch liền kép (P-4) cấm vượt tuyệt đối và cấm đi vào - có hiệu lực mọi lúc, ngay cả khi không có biển báo.'),

-- ============================================================
-- 6. TRAFFIC RULES - 5 questions
-- ============================================================

('special', 'W Polsce obowiązuje ruch:', 'Ở Ba Lan áp dụng giao thông:', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/PL_road_sign_C-18.svg/250px-PL_road_sign_C-18.svg.png', 'Prawostronny', 'Bên phải', 'Lewostronny', 'Bên trái', 'Dwustronny', 'Hai bên', 'A', 'W Polsce obowiązuje ruch prawostronny - pojazdy poruszają się po prawej stronie jezdni, a kierownica znajduje się po lewej stronie pojazdu.', 'Ở Ba Lan áp dụng giao thông bên phải - xe chạy ở phía phải đường và vô lăng ở phía trái xe.'),

('special', 'Czy wolno wyprzedzać pojazd na przejściu dla pieszych?', 'Có được phép vượt xe trên vạch sang đường cho người đi bộ không?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/PL_road_sign_D-6.svg/250px-PL_road_sign_D-6.svg.png', 'Tak, jeśli nie ma pieszych', 'Có, nếu không có người đi bộ', 'Tak, jeśli pojazd jedzie wolno', 'Có, nếu xe chạy chậm', 'Nie, jest to zabronione', 'Không, bị cấm', 'C', 'Wyprzedzanie na przejściu dla pieszych jest bezwzględnie zabronione. Wyjątek: na przejściu bez oznakowania poziomego można wyprzedzać, ale ostrożnie.', 'Vượt xe trên vạch sang đường cho người đi bộ bị cấm tuyệt đối. Ngoại lệ: trên vạch sang đường không có vạch kẻ ngang có thể vượt nhưng phải cẩn thận.'),

('special', 'Czy kierujący pojazdem może używać telefonu bez zestawu głośnomówiącego?', 'Người lái xe có thể sử dụng điện thoại không có bộ loa ngoài không?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', 'Tak, bez ograniczeń', 'Có, không giới hạn', 'Nie, jest to zabronione', 'Không, bị cấm', 'Tak, tylko w korku', 'Có, chỉ khi tắc đường', 'B', 'W Polsce używanie telefonu bez zestawu głośnomówiącego podczas jazdy jest zabronione i grozi mandatem.', 'Ở Ba Lan, sử dụng điện thoại không có bộ loa ngoài khi lái xe là bị cấm và bị phạt.'),

('special', 'Kto ma pierwszeństwo na skrzyżowaniu równorzędnym w Polsce?', 'Ai có quyền ưu tiên tại ngã tư ngang nhau ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Pojazd z prawej strony', 'Xe từ phía phải', 'Pojazd z lewej strony', 'Xe từ phía trái', 'Pojazd szybszy', 'Xe chạy nhanh hơn', 'A', 'Na skrzyżowaniu dróg równorzędnych w Polsce obowiązuje zasada prawej strony - pierwszeństwo ma pojazd nadjeżdżający z prawej strony.', 'Tại ngã tư các đường ngang nhau ở Ba Lan áp dụng quy tắc bên phải - xe đến từ phía phải có quyền ưu tiên.'),

('special', 'Czy wolno zawracać na autostradzie?', 'Có được quay đầu xe trên đường cao tốc không?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/PL_road_sign_E-17a.svg/250px-PL_road_sign_E-17a.svg.png', 'Tak, w wyznaczonych miejscach', 'Có, ở nơi quy định', 'Tak, na pasie awaryjnym', 'Có, trên làn khẩn cấp', 'Nie, jest to surowo zabronione', 'Không, bị cấm nghiêm ngặt', 'C', 'Zawracanie na autostradzie jest surowo zabronione. Nie wolno też cofać, jechać pod prąd ani zatrzymywać się poza wyznaczonymi miejscami.', 'Quay đầu xe trên đường cao tốc bị cấm nghiêm ngặt. Cũng không được lùi xe, đi ngược chiều hoặc dừng ngoài những nơi quy định.'),

-- ============================================================
-- 7. VEHICLE EQUIPMENT - 5 questions
-- ============================================================

('special', 'Co jest obowiązkowym wyposażeniem każdego samochodu osobowego w Polsce?', 'Đồ gì là thiết bị bắt buộc của mọi xe ô tô con ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/PL_road_sign_C-9.svg/250px-PL_road_sign_C-9.svg.png', 'Apteczka pierwszej pomocy', 'Hộp sơ cứu', 'Trójkąt ostrzegawczy', 'Tam giác cảnh báo', 'Gaśnica', 'Bình chữa cháy', 'B', 'Trójkąt ostrzegawczy jest obowiązkowym wyposażeniem każdego samochodu osobowego w Polsce. Apteczka jest zalecana, gaśnica wymagana w niektórych przypadkach.', 'Tam giác cảnh báo là thiết bị bắt buộc của mọi xe ô tô con ở Ba Lan. Hộp sơ cứu được khuyến khích, bình chữa cháy bắt buộc trong một số trường hợp.'),

('special', 'Jaki minimalny bieżnik opony jest dopuszczalny w Polsce?', 'Độ sâu lốp tối thiểu được phép ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PL_road_sign_D-7.svg/250px-PL_road_sign_D-7.svg.png', '1,0 mm', '1,0 mm', '1,6 mm', '1,6 mm', '2,0 mm', '2,0 mm', 'B', 'Minimalna głębokość bieżnika opony w Polsce wynosi 1,6 mm. Poniżej tej wartości opona jest uznawana za zużytą i nie może być używana.', 'Độ sâu lốp tối thiểu ở Ba Lan là 1,6 mm. Dưới giá trị này lốp được coi là mòn và không được sử dụng.'),

('special', 'W jakich okresach roku w Polsce obowiązuje obowiązek używania świateł mijania?', 'Ở Ba Lan, vào những thời kỳ nào trong năm bắt buộc phải sử dụng đèn chiếu gần?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/PL_road_sign_A-30.svg/250px-PL_road_sign_A-30.svg.png', 'Tylko zimą', 'Chỉ mùa đông', 'Cały rok, przez całą dobę', 'Cả năm, suốt ngày đêm', 'Tylko w nocy', 'Chỉ ban đêm', 'B', 'W Polsce obowiązek używania świateł mijania obowiązuje przez cały rok i całą dobę - także w dzień.', 'Ở Ba Lan, bắt buộc sử dụng đèn chiếu gần suốt cả năm và suốt ngày đêm - kể cả ban ngày.'),

('special', 'Jaki jest minimalny wiek osoby, która może prowadzić samochód osobowy z kategorią B w Polsce?', 'Tuổi tối thiểu của người có thể lái xe ô tô con hạng B ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/PL_road_sign_B-18.svg/250px-PL_road_sign_B-18.svg.png', '16 lat', '16 tuổi', '17 lat', '17 tuổi', '18 lat', '18 tuổi', 'C', 'Minimalny wiek do prowadzenia samochodu osobowego (kategoria B) w Polsce wynosi 18 lat. Wcześniej (17 lat) można uzyskać prawo jazdy, ale z ograniczeniami i pod nadzorem.', 'Tuổi tối thiểu để lái xe ô tô con (hạng B) ở Ba Lan là 18 tuổi. Trước đó (17 tuổi) có thể có bằng lái nhưng bị giới hạn và phải có người giám sát.'),

('special', 'Ile wynosi maksymalne dopuszczalne stężenie alkoholu we krwi kierowcy w Polsce?', 'Nồng độ cồn tối đa cho phép trong máu của người lái xe ở Ba Lan là bao nhiêu?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', '0,0 promila', '0,0 phần nghìn', '0,2 promila', '0,2 phần nghìn', '0,5 promila', '0,5 phần nghìn', 'B', 'W Polsce obowiązuje limit 0,2 promila alkoholu we krwi. Od 2024 roku planowane jest zaostrzenie do 0,0 promila dla kierowców z krótkim stażem. Dla wszystkich kierowców obecnie 0,2‰.', 'Ở Ba Lan áp dụng giới hạn 0,2 phần nghìn cồn trong máu. Từ năm 2024 có kế hoạch siết chặt xuống 0,0 đối với lái xe mới. Hiện tại áp dụng 0,2‰ cho tất cả.'),

-- ============================================================
-- 8. ALCOHOL/DRUGS - 5 questions
-- ============================================================

('special', 'Co się stanie, jeśli kierowca zostanie złapany na jeździe pod wpływem alkoholu (powyżej 0,5 promila) w Polsce?', 'Điều gì sẽ xảy ra nếu người lái xe bị bắt lái xe khi có nồng độ cồn (trên 0,5 phần nghìn) ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', 'Tylko mandat', 'Chỉ phạt tiền', 'Zatrzymanie prawa jazdy, mandat i kara pozbawienia wolności do 2 lat', 'Tước bằng, phạt tiền và phạt tù đến 2 năm', 'Tylko pouczenie', 'Chỉ nhắc nhở', 'B', 'Prowadzenie pojazdu w stanie nietrzeźwości (powyżej 0,5 promila) w Polsce jest przestępstwem - grozi kara pozbawienia wolności do 2 lat, utrata prawa jazdy i wysoki mandat.', 'Lái xe khi say rượu (trên 0,5 phần nghìn) ở Ba Lan là trọng tội - có thể bị phạt tù đến 2 năm, tước bằng lái và phạt tiền cao.'),

('special', 'Jak długo po wypiciu alkoholu nie powinno się prowadzić samochodu?', 'Bao lâu sau khi uống rượu thì không nên lái xe?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', '1 godzinę', '1 giờ', '2-3 godziny', '2-3 giờ', 'Minimum 6-8 godzin', 'Tối thiểu 6-8 giờ', 'C', 'Alkohol pozostaje w organizmie przez wiele godzin. Standardowe piwo (0,5l) jest metabolizowane przez około 2-3 godziny, ale dla bezpieczeństwa zaleca się minimum 6-8 godzin przerwy przed prowadzeniem pojazdu.', 'Rượu còn trong cơ thể nhiều giờ. Một lon bia tiêu chuẩn (0,5l) được chuyển hóa trong khoảng 2-3 giờ, nhưng để an toàn nên chờ tối thiểu 6-8 giờ trước khi lái xe.'),

('special', 'Czy kierowca może odmówić badania alkomatem w Polsce?', 'Người lái xe có thể từ chối kiểm tra nồng độ cồn ở Ba Lan không?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', 'Tak, bez konsekwencji', 'Có, không bị phạt', 'Tak, ale może zostać poddany badaniu krwi', 'Có, nhưng có thể bị xét nghiệm máu', 'Nie, to niemożliwe', 'Không, không thể', 'B', 'Kierowca ma prawo odmówić badania alkomatem, ale wtedy policja ma prawo skierować go na badanie krwi. Odmowa obu badań jest traktowana jako przyznanie się do winy.', 'Người lái xe có quyền từ chối kiểm tra nồng độ cồn bằng ống thổi, nhưng khi đó cảnh sát có quyền yêu cầu xét nghiệm máu. Từ chối cả hai bị coi là nhận tội.'),

('special', 'Które leki mogą wpływać na zdolność prowadzenia pojazdu?', 'Loại thuốc nào có thể ảnh hưởng đến khả năng lái xe?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/PL_road_sign_B-9.svg/250px-PL_road_sign_B-9.svg.png', 'Tylko antybiotyki', 'Chỉ kháng sinh', 'Leki uspokajające, nasenne i psychotropowe', 'Thuốc an thần, thuốc ngủ và thuốc tâm thần', 'Żadne leki', 'Không có thuốc nào', 'B', 'Leki uspokajające, nasenne, przeciwdepresyjne i psychotropowe mogą znacząco wpływać na zdolność prowadzenia pojazdu. Zawsze należy czytać ulotkę lub konsultować się z lekarzem.', 'Thuốc an thần, thuốc ngủ, thuốc chống trầm cảm và thuốc tâm thần có thể ảnh hưởng đáng kể đến khả năng lái xe. Luôn đọc tờ hướng dẫn hoặc tham khảo bác sĩ.'),

('special', 'Ile piwa (0,5 l, 5% alkoholu) trzeba wypić, aby przekroczyć limit 0,2 promila?', 'Cần uống bao nhiêu bia (0,5 l, 5% cồn) để vượt quá giới hạn 0,2 phần nghìn?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PL_road_sign_B-5.svg/250px-PL_road_sign_B-5.svg.png', '5 piw', '5 lon bia', '1-2 piwa', '1-2 lon bia', '10 piw', '10 lon bia', 'B', 'Dla osoby o wadze ok. 70 kg już 1-2 piwa mogą spowodować przekroczenie limitu 0,2 promila. Czasami wystarczy nawet jedno piwo.', 'Đối với người nặng khoảng 70 kg, 1-2 lon bia có thể vượt quá giới hạn 0,2 phần nghìn. Đôi khi chỉ cần một lon bia.'),

-- ============================================================
-- 9. FIRST AID BASICS - 5 questions
-- ============================================================

('special', 'Co należy zrobić w pierwszej kolejności na miejscu wypadku drogowego?', 'Điều đầu tiên cần làm tại hiện trường tai nạn giao thông là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Natychmiast ewakuować poszkodowanych', 'Ngay lập tức sơ tán nạn nhân', 'Zabezpieczyć miejsce wypadku i wezwać pomoc', 'Bảo vệ hiện trường và gọi cứu hộ', 'Sprawdzić dokumenty', 'Kiểm tra giấy tờ', 'B', 'Pierwszy krok na miejscu wypadku to zabezpieczenie miejsca (włączenie świateł awaryjnych, ustawienie trójkąta) i wezwanie pomocy (tel. 112). Bezpieczeństwo jest najważniejsze.', 'Bước đầu tiên tại hiện trường tai nạn là bảo vệ hiện trường (bật đèn khẩn cấp, đặt tam giác cảnh báo) và gọi cứu hộ (số 112). An toàn là quan trọng nhất.'),

('special', 'Pod jaki numer należy dzwonić w razie wypadku drogowego w Polsce?', 'Số điện thoại nào cần gọi khi xảy ra tai nạn giao thông ở Ba Lan?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', '999', '999', '112', '112', '997', '997', 'B', 'Numer alarmowy w Polsce to 112 (europejski numer alarmowy). Można też dzwonić pod 997 (policja), 998 (straż pożarna), 999 (pogotowie).', 'Số khẩn cấp ở Ba Lan là 112 (số khẩn cấp châu Âu). Cũng có thể gọi 997 (cảnh sát), 998 (cứu hỏa), 999 (cấp cứu).'),

('special', 'Jak udrożnić drogi oddechowe u nieprzytomnej osoby?', 'Làm thế nào để thông đường thở cho người bất tỉnh?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Ułożyć w pozycji siedzącej', 'Đặt ở tư thế ngồi', 'Odchylić głowę do tyłu i unieść brodę', 'Nghiêng đầu ra sau và nâng cằm', 'Położyć na brzuchu', 'Đặt nằm sấp', 'B', 'Aby udrożnić drogi oddechowe u nieprzytomnej osoby, należy odchylić głowę do tyłu i unieść brodę (tzw. rękoczyn Esmarcha).', 'Để thông đường thở cho người bất tỉnh, cần nghiêng đầu ra sau và nâng cằm (gọi là nghiệm pháp Esmarch).'),

('special', 'Jak często należy wykonywać masaż serca u osoby z zatrzymaniem krążenia?', 'Mỗi lần nên thực hiện ép tim ngoài lồng ngực cho người ngừng tuần hoàn như thế nào?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', '30 uciśnięć na 2 oddechy, 100-120/min', '30 lần ép cho 2 nhịp thở, 100-120/phút', '60 uciśnięć na 1 oddech', '60 lần ép cho 1 nhịp thở', '100 uciśnięć bez oddechów', '100 lần ép không thở', 'A', 'Standardowo wykonuje się 30 uciśnięć klatki piersiowej na 2 oddechy ratownicze, z częstotliwością 100-120 uciśnięć na minutę. Głębokość uciśnięć: 5-6 cm.', 'Tiêu chuẩn là 30 lần ép ngực cho 2 nhịp thở cấp cứu, với tần suất 100-120 lần/phút. Độ sâu ép: 5-6 cm.'),

('special', 'Co to jest pozycja bezpieczna (pozycja boczna ustalona)?', 'Tư thế an toàn (tư thế nằm nghiêng ổn định) là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/PL_road_sign_A-8.svg/250px-PL_road_sign_A-8.svg.png', 'Pozycja na plecach', 'Tư thế nằm ngửa', 'Pozycja na boku z głową odchyloną', 'Tư thế nằm nghiêng với đầu nghiêng ra sau', 'Pozycja na brzuchu', 'Tư thế nằm sấp', 'B', 'Pozycja boczna ustalona (pozycja bezpieczna) to pozycja na boku, która zapobiega zadławieniu i utrzymuje drożność dróg oddechowych u nieprzytomnej, oddychającej osoby.', 'Tư thế nằm nghiêng ổn định (tư thế an toàn) là tư thế nằm nghiêng giúp tránh nghẹn và duy trì thông đường thở cho người bất tỉnh nhưng còn thở được.'),

-- ============================================================
-- 10. ENVIRONMENTAL DRIVING (Eco-driving) - 5 questions
-- ============================================================

('special', 'Co to jest ekojazda?', 'Lái xe sinh thái là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Jazda na pełnych obrotach silnika', 'Lái xe với ga hết cỡ', 'Styl jazdy zmniejszający zużycie paliwa i emisję spalin', 'Phong cách lái giảm tiêu hao nhiên liệu và khí thải', 'Jazda tylko po autostradzie', 'Chỉ lái xe trên đường cao tốc', 'B', 'Ekojazda to styl jazdy, który minimalizuje zużycie paliwa i emisję spalin. Obejmuje płynne przyspieszanie, unikanie gwałtownych hamowań i utrzymywanie stałej prędkości.', 'Lái xe sinh thái là phong cách lái giảm thiểu tiêu hao nhiên liệu và khí thải. Bao gồm tăng tốc êm, tránh phanh gấp và duy trì tốc độ ổn định.'),

('special', 'Która z poniższych praktyk jest elementem ekojazdy?', 'Thực hành nào sau đây là một phần của lái xe sinh thái?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Gwałtowne przyspieszanie', 'Tăng tốc đột ngột', 'Płynne przyspieszanie i hamowanie', 'Tăng tốc và phanh êm', 'Jazda na najwyższym biegu w mieście', 'Chạy số cao nhất trong thành phố', 'B', 'Ekojazda obejmuje płynne przyspieszanie i hamowanie, unikanie biegu jałowego, jazdę na najwyższym możliwym biegu i przewidywanie sytuacji na drodze.', 'Lái xe sinh thái bao gồm tăng tốc và phanh êm, tránh chạy không tải, chạy số cao nhất có thể và dự đoán tình huống trên đường.'),

('special', 'Jak prawidłowo hamować w ekojazdzie?', 'Cách phanh đúng trong lái xe sinh thái là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Gwałtownie hamować', 'Phanh đột ngột', 'Hamować silnikiem i płynnie', 'Phanh bằng động cơ và êm', 'Nie hamować wcale', 'Không phanh', 'B', 'Ekojazda preferuje hamowanie silnikiem (zjeżdżanie na biegu) zamiast gwałtownego hamowania hamulcem. To oszczędza paliwo i zmniejsza zużycie hamulców.', 'Lái xe sinh thái ưu tiên phanh bằng động cơ (chạy xe bằng số thấp khi xuống dốc) thay vì phanh gấp bằng phanh. Tiết kiệm nhiên liệu và giảm mòn phanh.'),

('special', 'Co to jest Start-Stop w samochodzie?', 'Hệ thống Start-Stop trên xe ô tô là gì?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'System grzewczy', 'Hệ thống sưởi', 'System automatycznie wyłączający silnik na postoju', 'Hệ thống tự động tắt máy khi dừng', 'System klimatyzacji', 'Hệ thống điều hòa', 'B', 'System Start-Stop automatycznie wyłącza silnik, gdy pojazd stoi (np. na światłach) i uruchamia go ponownie po naciśnięciu sprzęgła lub gazu. Oszczędza paliwo i zmniejsza emisję.', 'Hệ thống Start-Stop tự động tắt máy khi xe dừng (ví dụ tại đèn đỏ) và khởi động lại khi nhấn côn hoặc ga. Tiết kiệm nhiên liệu và giảm khí thải.'),

('special', 'W jakiej temperaturze silnik spala najmniej paliwa?', 'Ở nhiệt độ nào động cơ tiêu hao nhiên liệu ít nhất?', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PL_road_sign_C-13.svg/250px-PL_road_sign_C-13.svg.png', 'Zaraz po uruchomieniu', 'Ngay sau khi khởi động', 'Po rozgrzaniu do temperatury roboczej', 'Sau khi làm nóng đến nhiệt độ hoạt động', 'W niskiej temperaturze', 'Ở nhiệt độ thấp', 'B', 'Silnik spala najmniej paliwa po rozgrzaniu do temperatury roboczej (ok. 90°C). Zimny silnik zużywa znacznie więcej paliwa, dlatego nie zaleca się długiego rozgrzewania na postoju.', 'Động cơ tiêu hao nhiên liệu ít nhất sau khi làm nóng đến nhiệt độ hoạt động (khoảng 90°C). Động cơ lạnh tiêu hao nhiều nhiên liệu hơn nhiều, vì vậy không nên làm nóng lâu khi dừng.');

-- ============================================================
-- END OF 50 QUESTIONS
-- ============================================================